# Text tagging with NLTK

In [1]:
# This may or may not be necessary for you. Gives python permission to access the internet so we can download libraries.

import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

In [2]:
#import relevant nltk data, functions

import nltk
from nltk import word_tokenize,pos_tag
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/bcritt/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /Users/bcritt/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /Users/bcritt/nltk_data...
[nltk_data]   Package words is already up-to-date!

True

In [3]:
# Read in a directory of txt files as the corpus using the os library.

import os
corpusdir = '/Users/bcritt/Documents/StanfordProjects/Corpora/Emerson/emerson/'
corpus = []
for infile in os.listdir(corpusdir):
    with open(corpusdir+infile, errors='ignore') as fin:
        corpus.append(fin.read())

In [9]:
# Do parts of speech tagging of corpus
pos = pos_tag(word_tokenize(corpus[0]))
pos

[('SAMUEL', 'NNP'),
 ('HOAR', 'NNP'),
 ('.', '.'),
 ('“', 'VB'),
 ('Magno', 'NNP'),
 ('southeast', 'JJ'),
 ('judice', 'NN'),
 ('quisque', 'NN'),
 ('tuetur', 'NN'),
 (';', ':'),
 ('Victrix', 'NNP'),
 ('causa', 'VBP'),
 ('deis', 'NN'),
 ('placuit', 'NN'),
 ('sed', 'VBD'),
 ('victa', 'JJ'),
 ('Catoni.', 'NNP'),
 ('”', 'NN'),
 ('A', 'NNP'),
 ('YEAR', 'NN'),
 ('ago', 'RB'),
 (',', ','),
 ('how', 'WRB'),
 ('often', 'RB'),
 ('did', 'VBD'),
 ('we', 'PRP'),
 ('meet', 'VB'),
 ('Beneath', 'IN'),
 ('these', 'DT'),
 ('elms', 'NNS'),
 (',', ','),
 ('once', 'RB'),
 ('more', 'RBR'),
 ('in', 'IN'),
 ('sober', 'NNP'),
 ('bloom', 'NN'),
 (',', ','),
 ('Thy', 'NNP'),
 ('tall', 'NN'),
 (',', ','),
 ('sad', 'JJ'),
 ('figure', 'NN'),
 ('pacing', 'VBG'),
 ('down', 'RP'),
 ('the', 'DT'),
 ('street', 'NN'),
 (',', ','),
 ('And', 'CC'),
 ('now', 'RB'),
 ('the', 'DT'),
 ('robin', 'NN'),
 ('sings', 'NNS'),
 ('above', 'IN'),
 ('thy', 'JJ'),
 ('tomb', 'NN'),
 ('!', '.'),
 ('Thy', 'NNP'),
 ('name', 'NN'),
 ('on', 'IN'),
 ('other', 'JJ'),
 ('shores', 'NNS'),
 ('may', 'MD'),
 ('never', 'RB'),
 ('be', 'VB'),
 ('known', 'VBN'),
 (',', ','),
 ('Though', 'IN'),
 ('Rome', 'NNP'),
 ('austere', 'RB'),
 ('no', 'DT'),
 ('graver', 'NN'),
 ('consul', 'NN'),
 ('knew', 'VBD'),
 (',', ','),
 ('But', 'CC'),
 ('Massachusetts', 'NNP'),
 ('her', 'PRP$'),
 ('true', 'JJ'),
 ('son', 'NN'),
 ('shall', 'MD'),
 ('own', 'VB'),
 (';', ':'),
 ('Out', 'NNP'),
 ('of', 'IN'),
 ('her', 'PRP$'),
 ('soil', 'NN'),
 ('thy', 'NN'),
 ('hardy', 'NN'),
 ('virtues', 'NNS'),
 ('grew', 'VBD'),
 ('.', '.'),
 ('She', 'PRP'),
 ('loves', 'VBZ'),
 ('the', 'DT'),
 ('man', 'NN'),
 ('that', 'WDT'),
 ('chose', 'VBD'),
 ('the', 'DT'),
 ('conquered', 'JJ'),
 ('cause', 'NN'),
 (',', ','),
 ('With', 'IN'),
 ('upright', 'JJ'),
 ('soul', 'NN'),
 ('that', 'WDT'),
 ('bowed', 'VBD'),
 ('to', 'TO'),
 ('God', 'NNP'),
 ('alone', 'RB'),
 (';', ':'),
 ('The', 'DT'),
 ('clean', 'JJ'),
 ('hands', 'NNS'),
 ('that', 'WDT'),
 ('upheld', 'VBD'),
 ('her', 'PRP'),
 ('equal', 'JJ'),
 ('laws', 'NNS'),
 (',', ','),
 ('The', 'DT'),
 ('old', 'JJ'),
 ('religion', 'NN'),
 ('never', 'RB'),
 ('to', 'TO'),
 ('be', 'VB'),
 ('outgrown', 'VBN'),
 (';', ':'),
 ('The', 'DT'),
 ('cold', 'JJ'),
 ('demeanour', 'NN'),
 (',', ','),
 ('the', 'DT'),
 ('warm', 'JJ'),
 ('heart', 'NN'),
 ('beneath', 'NN'),
 (',', ','),
 ('The', 'DT'),
 ('simple', 'JJ'),
 ('grandeur', 'NN'),
 ('of', 'IN'),
 ('thy', 'JJ'),
 ('life', 'NN'),
 ('and', 'CC'),
 ('death', 'NN'),
 ('.', '.'),
 ('F.', 'NNP'),
 ('B.', 'NNP'),
 ('SANBORN', 'NNP'),
 ('.', '.'),
 ('April', 'NNP'),
 (',', ','),
 ('1857', 'CD'),
 ('.', '.'),
 ('SAMUEL', 'NNP'),
 ('HOAR', 'NNP'),
 ('.', '.'),
 ('HERE', 'NNP'),
 ('is', 'VBZ'),
 ('a', 'DT'),
 ('day', 'NN'),
 ('on', 'IN'),
 ('which', 'WDT'),
 ('more', 'RBR'),
 ('public', 'JJ'),
 ('good', 'JJ'),
 ('or', 'CC'),
 ('evil', 'JJ'),
 ('is', 'VBZ'),
 ('to', 'TO'),
 ('be', 'VB'),
 ('done', 'VBN'),
 ('than', 'IN'),
 ('was', 'VBD'),
 ('ever', 'RB'),
 ('done', 'VBN'),
 ('on', 'IN'),
 ('any', 'DT'),
 ('day', 'NN'),
 ('.', '.'),
 ('And', 'CC'),
 ('this', 'DT'),
 ('is', 'VBZ'),
 ('the', 'DT'),
 ('pregnant', 'JJ'),
 ('season', 'NN'),
 (',', ','),
 ('when', 'WRB'),
 ('our', 'PRP$'),
 ('old', 'JJ'),
 ('Roman', 'NNP'),
 (',', ','),
 ('Samuel', 'NNP'),
 ('Hoar', 'NNP'),
 (',', ','),
 ('has', 'VBZ'),
 ('chosen', 'VBN'),
 ('to', 'TO'),
 ('quit', 'VB'),
 ('this', 'DT'),
 ('world', 'NN'),
 ('.', '.'),
 ('Ab', 'NNP'),
 ('iniquo', 'JJ'),
 ('certamine', 'NN'),
 ('indignabundus', 'NN'),
 ('recessit', 'NN'),
 ('.', '.'),
 ('He', 'PRP'),
 ('was', 'VBD'),
 ('born', 'VBN'),
 ('under', 'IN'),
 ('a', 'DT'),
 ('Christian', 'JJ'),
 ('and', 'CC'),
 ('humane', 'JJ'),
 ('star', 'NN'),
 (',', ','),
 ('full', 'JJ'),
 ('of', 'IN'),
 ('mansuetude', 'NN'),
 ('and', 'CC'),
 ('nobleness', 'NN'),
 (',', ','),
 ('honour', 'NN'),
 ('and', 'CC'),
 ('charity', 'NN'),
 (';', ':'),
 ('and', 'CC'),
 (',', ','),
 ('whilst', 'VBD'),
 ('he', 'PRP'),
 ('was', 'VBD'),
 ('willing', 'JJ'),
 ('to', 'TO'),
 ('face', 'VB'),
 ('every', 'DT'),
 ('disagreeable', 'JJ'),
 ('duty', 'NN'),
 (',', ','),
 ('whilst', 'NN'),
 ('he', 'PRP'),
 ('dared', 'VBD'),
 ('to', 'TO'),
 ('do', 'VB'),
 ('all', 'DT'),
 ('that', 'WDT'),
 ('might', 'MD'),
 ('beseem', 'VB'),
 ('a', 'DT'),
 ('man', 'NN'),
 (',', ','),
 ('his', 'PRP$'),
 ('self', 'NN'),
 ('respect', 'NN'),
 ('restrained', 'VBD'),
 ('him', 'PRP'),
 ('from', 'IN'),
 ('any', 'DT'),
 ('foolhardiness', 'NN'),
 ('.', '.'),
 ('The', 'DT'),
 ('Homeric', 'NNP'),
 ('heroes', 'NNS'),
 (',', ','),
 ('when', 'WRB'),
 ('they', 'PRP'),
 ('saw', 'VBD'),
 ('the', 'DT'),
 ('gods', 'NNS'),
 ('mingling', 'VBG'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('fray', 'NN'),
 (',', ','),
 ('sheathed', 'VBD'),
 ('their', 'PRP$'),
 ('swords', 'NNS'),
 ('.', '.'),
 ('So', 'RB'),
 ('did', 'VBD'),
 ('not', 'RB'),
 ('he', 'PRP'),
 ('feel', 'VB'),
 ('any', 'DT'),
 ('call', 'NN'),
 ('to', 'TO'),
 ('make', 'VB'),
 ('it', 'PRP'),
 ('a', 'DT'),
 ('contest', 'NN'),
 ('of', 'IN'),
 ('personal', 'JJ'),
 ('strength', 'NN'),
 ('with', 'IN'),
 ('mobs', 'NN'),
 ('or', 'CC'),
 ('nations', 'NNS'),
 (';', ':'),
 ('but', 'CC'),
 ('when', 'WRB'),
 ('he', 'PRP'),
 ('saw', 'VBD'),
 ('the', 'DT'),
 ('day', 'NN'),
 ('and', 'CC'),
 ('the', 'DT'),
 ('gods', 'NNS'),
 ('went', 'VBD'),
 ('against', 'IN'),
 ('him', 'PRP'),
 (',', ','),
 ('he', 'PRP'),
 ('withdrew', 'VBD'),
 (',', ','),
 ('but', 'CC'),
 ('with', 'IN'),
 ('an', 'DT'),
 ('unaltered', 'JJ'),
 ('belief', 'NN'),
 ('.', '.'),
 ('All', 'DT'),
 ('was', 'VBD'),
 ('conquered', 'VBN'),
 ('prœter', 'NN'),
 ('atrocem', 'NN'),
 ('animum', 'JJ'),
 ('Catonis', 'NNP'),
 ('.', '.'),
 ('At', 'IN'),
 ('the', 'DT'),
 ('time', 'NN'),
 ('when', 'WRB'),
 ('he', 'PRP'),
 ('went', 'VBD'),
 ('to', 'TO'),
 ('South', 'NNP'),
 ('Carolina', 'NNP'),
 ('as', 'IN'),
 ('the', 'DT'),
 ('Commissioner', 'NNP'),
 ('of', 'IN'),
 ('Massachusetts', 'NNP'),
 (',', ','),
 ('in', 'IN'),
 ('1844', 'CD'),
 (',', ','),
 ('whilst', 'VBD'),
 ('staying', 'VBG'),
 ('in', 'IN'),
 ('Charleston', 'NNP'),
 (',', ','),
 ('pending', 'VBG'),
 ('his', 'PRP$'),
 ('correspondence', 'NN'),
 ('with', 'IN'),
 ('the', 'DT'),
 ('governor', 'NN'),
 ('and', 'CC'),
 ('the', 'DT'),
 ('legal', 'JJ'),
 ('officers', 'NNS'),
 (',', ','),
 ('he', 'PRP'),
 ('was', 'VBD'),
 ('repeatedly', 'RB'),
 ('warned', 'VBN'),
 ('that', 'IN'),
 ('it', 'PRP'),
 ('was', 'VBD'),
 ('not', 'RB'),
 ('safe', 'JJ'),
 ('for', 'IN'),
 ('him', 'PRP'),
 ('to', 'TO'),
 ('appear', 'VB'),
 ('in', 'IN'),
 ('public', 'JJ'),
 (',', ','),
 ('or', 'CC'),
 ('to', 'TO'),
 ('take', 'VB'),
 ('his', 'PRP$'),
 ('daily', 'JJ'),
 ('walk', 'NN'),
 (',', ','),
 ('as', 'IN'),
 ('he', 'PRP'),
 ('had', 'VBD'),
 ('done', 'VBN'),
 (',', ','),
 ('unattended', 'VBN'),
 ('by', 'IN'),
 ('his', 'PRP$'),
 ('friends', 'NNS'),
 (',', ','),
 ('in', 'IN'),
 ('the', 'DT'),
 ('streets', 'NNS'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('city', 'NN'),
 ('.', '.'),
 ('He', 'PRP'),
 ('was', 'VBD'),
 ('advised', 'VBN'),
 ('to', 'TO'),
 ('withdraw', 'VB'),
 ('to', 'TO'),
 ('private', 'JJ'),
 ('lodgings', 'NNS'),
 (',', ','),
 ('which', 'WDT'),
 ('were', 'VBD'),
 ('eagerly', 'RB'),
 ('offered', 'VBN'),
 ('him', 'PRP'),
 ('by', 'IN'),
 ('friends', 'NNS'),
 ('.', '.'),
 ('He', 'PRP'),
 ('rejected', 'VBD'),
 ('the', 'DT'),
 ('advice', 'NN'),
 (',', ','),
 ('and', 'CC'),
 ('refused', 'VBD'),
 ('the', 'DT'),
 ('offers', 'NNS'),
 (',', ','),
 ('saying', 'VBG'),
 ('that', 'IN'),
 ('he', 'PRP'),
 ('was', 'VBD'),
 ('old', 'JJ'),
 (',', ','),
 ('and', 'CC'),
 ('his', 'PRP$'),
 ('life', 'NN'),
 ('was', 'VBD'),
 ('not', 'RB'),
 ('worth', 'JJ'),
 ('much', 'RB'),
 (',', ','),
 ('but', 'CC'),
 ('he', 'PRP'),
 ('had', 'VBD'),
 ('rather', 'RB'),
 ('the', 'DT'),
 ('boys', 'NNS'),
 ('should', 'MD'),
 ('troll', 'VB'),
 ('his', 'PRP$'),
 ('old', 'JJ'),
 ('head', 'NN'),
 ('like', 'IN'),
 ('a', 'DT'),
 ('football', 'NN'),
 ('in', 'IN'),
 ('their', 'PRP$'),
 ('streets', 'NNS'),
 (',', ','),
 ('than', 'IN'),
 ('that', 'IN'),
 ('he', 'PRP'),
 ('should', 'MD'),
 ('hide', 'VB'),
 ('it', 'PRP'),
 ('.', '.'),
 ('And', 'CC'),
 ('he', 'PRP'),
 ('continued', 'VBD'),
 ('the', 'DT'),
 ('uniform', 'JJ'),
 ('practice', 'NN'),
 ('of', 'IN'),
 ('his', 'PRP$'),
 ('daily', 'JJ'),
 ('walk', 'NN'),
 ('into', 'IN'),
 ('all', 'DT'),
 ('parts', 'NNS'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('city', 'NN'),
 ('.', '.'),
 ('But', 'CC'),
 ('when', 'WRB'),
 ('the', 'DT'),
 ('mob', 'NN'),
 ('of', 'IN'),
 ('Charleston', 'NNP'),
 ('was', 'VBD'),
 ('assembled', 'VBN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('streets', 'NNS'),
 ('before', 'IN'),
 ('his', 'PRP$'),
 ('hotel', 'NN'),
 (',', ','),
 ('and', 'CC'),
 ('a', 'DT'),
 ('deputation', 'NN'),
 ('of', 'IN'),
 ('gentlemen', 'NNS'),
 ('waited', 'VBN'),
 ('upon', 'IN'),
 ('him', 'PRP'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('hall', 'NN'),
 ('to', 'TO'),
 ('say', 'VB'),
 ('they', 'PRP'),
 ('had', 'VBD'),
 ('come', 'VBN'),
 ('with', 'IN'),
 ('the', 'DT'),
 ('unanimous', 'JJ'),
 ('voice', 'NN'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('State', 'NNP'),
 ('to', 'TO'),
 ('remove', 'VB'),
 ('him', 'PRP'),
 ('by', 'IN'),
 ('force', 'NN'),
 (',', ','),
 ('and', 'CC'),
 ('the', 'DT'),
 ('carriage', 'NN'),
 ('was', 'VBD'),
 ('at', 'IN'),
 ('the', 'DT'),
 ('door', 'NN'),
 (',', ','),
 ('he', 'PRP'),
 ('considered', 'VBD'),
 ('his', 'PRP$'),
 ('duty', 'NN'),
 ('discharged', 'VBD'),
 ('to', 'TO'),
 ('the', 'DT'),
 ('last', 'JJ'),
 ('point', 'NN'),
 ('of', 'IN'),
 ('possibility', 'NN'),
 ('.', '.'),
 ('The', 'DT'),
 ('force', 'NN'),
 ('was', 'VBD'),
 ('apparent', 'JJ'),
 ('and', 'CC'),
 ('irresistible', 'JJ'),
 (';', ':'),
 ('the', 'DT'),
 ('legal', 'JJ'),
 ('officer', 'NN'),
 ("'s", 'POS'),
 ('part', 'NN'),
 ('was', 'VBD'),
 ('up', 'RB'),
 (';', ':'),
 ('it', 'PRP'),
 ('was', 'VBD'),
 ('now', 'RB'),
 ('time', 'NN'),
 ('for', 'IN'),
 ('the', 'DT'),
 ('military', 'JJ'),
 ('officer', 'NN'),
 ('to', 'TO'),
 ('be', 'VB'),
 ('sent', 'VBN'),
 (';', ':'),
 ('and', 'CC'),
 ('he', 'PRP'),
 ('said', 'VBD'),
 (',', ','),
 ('“', 'NNP'),
 ('Well', 'NNP'),
 (',', ','),
 ('gentlemen', 'NNS'),
 (',', ','),
 ('since', 'IN'),
 ('it', 'PRP'),
 ('is', 'VBZ'),
 ('your', 'PRP$'),
 ('pleasure', 'NN'),
 ('to', 'TO'),
 ('use', 'VB'),
 ('force', 'NN'),
 (',', ','),
 ('I', 'PRP'),
 ('must', 'MD'),
 ('go.', 'VB'),
 ('”', 'NN'),
 ('But', 'CC'),
 ('his', 'PRP$'),
 ('opinion', 'NN'),
 ('was', 'VBD'),
 ('unchanged', 'JJ'),
 ('.', '.'),
 ('In', 'IN'),
 ('like', 'JJ'),
 ('manner', 'NN'),
 ('now', 'RB'),
 (',', ','),
 ('when', 'WRB'),
 ('the', 'DT'),
 ('votes', 'NNS'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('Free', 'NNP'),
 ('States', 'NNPS'),
 (',', ','),
 ('as', 'IN'),
 ('shown', 'VBN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('recent', 'JJ'),
 ('election', 'NN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('State', 'NNP'),
 ('of', 'IN'),
 ('Pennsylvania', 'NNP'),
 (',', ','),
 ('had', 'VBD'),
 ('disappointed', 'VBN'),
 ('the', 'DT'),
 ('hopes', 'NNS'),
 ('of', 'IN'),
 ('mankind', 'NN'),
 ('and', 'CC'),
 ('betrayed', 'VBD'),
 ('the', 'DT'),
 ('cause', 'NN'),
 ('of', 'IN'),
 ('freedom', 'NN'),
 (',', ','),
 ('he', 'PRP'),
 ('considered', 'VBD'),
 ('the', 'DT'),
 ('question', 'NN'),
 ('of', 'IN'),
 ('justice', 'NN'),
 ('and', 'CC'),
 ('liberty', 'NN'),
 (',', ','),
 ('for', 'IN'),
 ('his', 'PRP$'),
 ('age', 'NN'),
 (',', ','),
 ('lost', 'VBN'),
 (',', ','),
 ('and', 'CC'),
 ('had', 'VBD'),
 ('no', 'DT'),
 ('longer', 'RBR'),
 ('the', 'DT'),
 ('will', 'MD'),
 ('to', 'TO'),
 ('drag', 'VB'),
 ('his', 'PRP$'),
 ('days', 'NNS'),
 ('through', 'IN'),
 ('the', 'DT'),
 ('dishonours', 'NN'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('long', 'JJ'),
 ('defeat', 'NN'),
 (',', ','),
 ('and', 'CC'),
 ('promptly', 'RB'),
 ('withdrew', 'VBD'),
 (',', ','),
 ('but', 'CC'),
 ('with', 'IN'),
 ('unaltered', 'JJ'),
 ('belief', 'NN'),
 ('.', '.'),
 ('He', 'PRP'),
 ('was', 'VBD'),
 ('a', 'DT'),
 ('very', 'RB'),
 ('natural', 'JJ'),
 (',', ','),
 ('but', 'CC'),
 ('a', 'DT'),
 ('very', 'RB'),
 ('high', 'JJ'),
 ('character', 'NN'),
 (';', ':'),
 ('a', 'DT'),
 ('man', 'NN'),
 ('of', 'IN'),
 ('simple', 'JJ'),
 ('tastes', 'NNS'),
 (',', ','),
 ('plain', 'NN'),
 ('and', 'CC'),
 ('true', 'JJ'),
 ('in', 'IN'),
 ('speech', 'NN'),
 (',', ','),
 ('with', 'IN'),
 ('a', 'DT'),
 ('clear', 'JJ'),
 ('perception', 'NN'),
 ('of', 'IN'),
 ('justice', 'NN'),
 (',', ','),
 ('and', 'CC'),
 ('a', 'DT'),
 ('perfect', 'JJ'),
 ('obedience', 'NN'),
 ('thereto', 'NN'),
 ('in', 'IN'),
 ('his', 'PRP$'),
 ('action', 'NN'),
 (';', ':'),
 ('of', 'IN'),
 ('a', 'DT'),
 ('strong', 'JJ'),
 ('understanding', 'NN'),
 (',', ','),
 ('precise', 'NN'),
 ('and', 'CC'),
 ('methodical', 'NN'),
 (',', ','),
 ('which', 'WDT'),
 ('gave', 'VBD'),
 ('him', 'PRP'),
 ('great', 'JJ'),
 ('eminence', 'NN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('legal', 'JJ'),
 ('profession', 'NN'),
 ('.', '.'),
 ('It', 'PRP'),
 ('was', 'VBD'),
 ('rather', 'RB'),
 ('his', 'PRP$'),
 ('reputation', 'NN'),
 ('for', 'IN'),
 ('severe', 'JJ'),
 ('method', 'NN'),
 ('in', 'IN'),
 ('his', 'PRP$'),
 ('intellect', 'NN'),
 ('than', 'IN'),
 ('any', 'DT'),
 ('special', 'JJ'),
 ('direction', 'NN'),
 ('in', 'IN'),
 ('his', 'PRP$'),
 ('studies', 'NNS'),
 ('that', 'WDT'),
 ('caused', 'VBD'),
 ('him', 'PRP'),
 ('to', 'TO'),
 ('be', 'VB'),
 ('offered', 'VBN'),
 ('the', 'DT'),
 ('mathematical', 'JJ'),
 ('chair', 'NN'),
 ('in', 'IN'),
 ('Harvard', 'NNP'),
 ('University', 'NNP'),
 (',', ','),
 ('when', 'WRB'),
 ('vacant', 'NN'),
 ('in', 'IN'),
 ('1806', 'CD'),
 ('.', '.'),
 ('The', 'DT'),
 ('severity', 'NN'),
 ('of', 'IN'),
 ('his', 'PRP$'),
 ('logic', 'NN'),
 ('might', 'MD'),
 ('have', 'VB'),
 ('inspired', 'VBN'),
 ('fear', 'NN'),
 (',', ','),
 ('had', 'VBD'),
 ('it', 'PRP'),
 ('not', 'RB'),
 ('been', 'VBN'),
 ('restrained', 'VBN'),
 ('by', 'IN'),
 ('his', 'PRP$'),
 ('natural', 'JJ'),
 ('reverence', 'NN'),
 (',', ','),
 ('which', 'WDT'),
 ('made', 'VBD'),
 ('him', 'PRP'),
 ('modest', 'JJ'),
 ('and', 'CC'),
 ('courteous', 'JJ'),
 (',', ','),
 ('though', 'IN'),
 ('his', 'PRP$'),
 ('courtesy', 'NN'),
 ('had', 'VBD'),
 ('a', 'DT'),
 ('grave', 'NN'),
 ('and', 'CC'),
 ('almost', 'RB'),
 ('military', 'JJ'),
 ('air', 'NN'),
 ('.', '.'),
 ('He', 'PRP'),
 ('combined', 'VBD'),
 ('a', 'DT'),
 ('uniform', 'JJ'),
 ('self', 'NN'),
 ('respect', 'NN'),
 ('with', 'IN'),
 ('a', 'DT'),
 ('natural', 'JJ'),
 ('reverence', 'NN'),
 ('for', 'IN'),
 ('every', 'DT'),
 ('other', 'JJ'),
 ('man', 'NN'),
 (';', ':'),
 ('so', 'CC'),
 ('that', 'IN'),
 ('it', 'PRP'),
 ('was', 'VBD'),
 ('perfectly', 'RB'),
 ('easy', 'JJ'),
 ('for', 'IN'),
 ('him', 'PRP'),
 ('to', 'TO'),
 ('associate', 'VB'),
 ('with', 'IN'),
 ('farmers', 'NNS'),
 (',', ','),
 ('and', 'CC'),
 ('with', 'IN'),
 ('plain', 'NN'),
 (',', ','),
 ('uneducated', 'JJ'),
 (',', ','),
 ('poor', 'JJ'),
 ('men', 'NNS'),
 (',', ','),
 ('and', 'CC'),
 ('he', 'PRP'),
 ('had', 'VBD'),
 ('a', 'DT'),
 ('strong', 'JJ'),
 (',', ','),
 ('unaffected', 'JJ'),
 ('interest', 'NN'),
 ('in', 'IN'),
 ('farms', 'NNS'),
 (',', ','),
 ('and', 'CC'),
 ('crops', 'NNS'),
 (',', ','),
 ('and', 'CC'),
 ('weathers', 'NNS'),
 (',', ','),
 ('and', 'CC'),
 ('the', 'DT'),
 ('common', 'JJ'),
 ('incidents', 'NNS'),
 ('of', 'IN'),
 ('rural', 'JJ'),
 ('life', 'NN'),
 ('.', '.'),
 ('It', 'PRP'),
 ('was', 'VBD'),
 ('just', 'RB'),
 ('as', 'IN'),
 ('easy', 'JJ'),
 ('for', 'IN'),
 ('him', 'PRP'),
 ('to', 'TO'),
 ('meet', 'VB'),
 ('on', 'IN'),
 ('the', 'DT'),
 ('same', 'JJ'),
 ('floor', 'NN'),
 (',', ','),
 ('and', 'CC'),
 ('with', 'IN'),
 ('the', 'DT'),
 ('same', 'JJ'),
 ('plain', 'NN'),
 ('courtesy', 'NN'),
 (',', ','),
 ('men', 'NNS'),
 ('of', 'IN'),
 ('distinction', 'NN'),
 ('and', 'CC'),
 ('large', 'JJ'),
 ('ability', 'NN'),
 ('.', '.'),
 ('He', 'PRP'),
 ('was', 'VBD'),
 ('fond', 'NN'),
 ('of', 'IN'),
 ('farms', 'NNS'),
 ('and', 'CC'),
 ('trees', 'NNS'),
 (',', ','),
 ('fond', 'NN'),
 ('of', 'IN'),
 ('birds', 'NNS'),
 (',', ','),
 ('and', 'CC'),
 ('attentive', 'JJ'),
 ('to', 'TO'),
 ('their', 'PRP$'),
 ('manners', 'NNS'),
 ('and', 'CC'),
 ('habits', 'NNS'),
 (';', ':'),
 ('addicted', 'VBN'),
 ('to', 'TO'),
 ('long', 'VB'),
 ('and', 'CC'),
 ('retired', 'JJ'),
 ('walks', 'NNS'),
 (';', ':'),
 ('temperate', 'VB'),
 ('to', 'TO'),
 ('asceticism', 'VB'),
 (',', ','),
 ('for', 'IN'),
 ('no', 'DT'),
 ('lesson', 'NN'),
 ('of', 'IN'),
 ('his', 'PRP$'),
 ('experience', 'NN'),
 ('was', 'VBD'),
 ('lost', 'VBN'),
 ('on', 'IN'),
 ('him', 'PRP'),
 (',', ','),
 ('and', 'CC'),
 ('his', 'PRP$'),
 ('self', 'NN'),
 ('command', 'NN'),
 ('was', 'VBD'),
 ('perfect', 'JJ'),
 ('.', '.'),
 ('Though', 'IN'),
 ('rich', 'JJ'),
 (',', ','),
 ('of', 'IN'),
 ('a', 'DT'),
 ('plainness', 'NN'),
 ('and', 'CC'),
 ('almost', 'RB'),
 ('poverty', 'NN'),
 ('of', 'IN'),
 ('personal', 'JJ'),
 ('expenditure', 'NN'),
 (',', ','),
 ('yet', 'RB'),
 ('liberal', 'JJ'),
 ('of', 'IN'),
 ('his', 'PRP$'),
 ('money', 'NN'),
 ('to', 'TO'),
 ('any', 'DT'),
 ('worthy', 'JJ'),
 ('use', 'NN'),
 (',', ','),
 ('readily', 'RB'),
 ('lending', 'VBG'),
 ('it', 'PRP'),
 ('to', 'TO'),
 ('young', 'JJ'),
 ('men', 'NNS'),
 (',', ','),
 ('and', 'CC'),
 ('industrious', 'JJ'),
 ('men', 'NNS'),
 (',', ','),
 ('and', 'CC'),
 ('by', 'IN'),
 ('no', 'DT'),
 ('means', 'NNS'),
 ('eager', 'VBP'),
 ('to', 'TO'),
 ('reclaim', 'VB'),
 ('of', 'IN'),
 ('them', 'PRP'),
 ('either', 'CC'),
 ...]

In [49]:
# Do named entity tagging of POS text
ne = nltk.ne_chunk(pos)

In [50]:
# see data
print(ne)

(S
  (ORGANIZATION SAMUEL/NNP)
  (GPE HOAR/NNP)
  ./.
  “/VB
  (PERSON Magno/NNP)
  southeast/JJ
  judice/NN
  quisque/NN
  tuetur/NN
  ;/:
  Victrix/NNP
  causa/VBP
  deis/NN
  placuit/NN
  sed/VBD
  victa/JJ
  Catoni./NNP
  ”/NN
  A/NNP
  YEAR/NN
  ago/RB
  ,/,
  how/WRB
  often/RB
  did/VBD
  we/PRP
  meet/VB
  Beneath/IN
  these/DT
  elms/NNS
  ,/,
  once/RB
  more/RBR
  in/IN
  sober/NNP
  bloom/NN
  ,/,
  (PERSON Thy/NNP)
  tall/NN
  ,/,
  sad/JJ
  figure/NN
  pacing/VBG
  down/RP
  the/DT
  street/NN
  ,/,
  And/CC
  now/RB
  the/DT
  robin/NN
  sings/NNS
  above/IN
  thy/JJ
  tomb/NN
  !/.
  Thy/NNP
  name/NN
  on/IN
  other/JJ
  shores/NNS
  may/MD
  never/RB
  be/VB
  known/VBN
  ,/,
  Though/IN
  (PERSON Rome/NNP)
  austere/RB
  no/DT
  graver/NN
  consul/NN
  knew/VBD
  ,/,
  But/CC
  (GPE Massachusetts/NNP)
  her/PRP$
  true/JJ
  son/NN
  shall/MD
  own/VB
  ;/:
  Out/NNP
  of/IN
  her/PRP$
  soil/NN
  thy/NN
  hardy/NN
  virtues/NNS
  grew/VBD
  ./.
  She/PRP
  loves/VBZ
  the/DT
  man/NN
  that/WDT
  chose/VBD
  the/DT
  conquered/JJ
  cause/NN
  ,/,
  With/IN
  upright/JJ
  soul/NN
  that/WDT
  bowed/VBD
  to/TO
  God/NNP
  alone/RB
  ;/:
  The/DT
  clean/JJ
  hands/NNS
  that/WDT
  upheld/VBD
  her/PRP
  equal/JJ
  laws/NNS
  ,/,
  The/DT
  old/JJ
  religion/NN
  never/RB
  to/TO
  be/VB
  outgrown/VBN
  ;/:
  The/DT
  cold/JJ
  demeanour/NN
  ,/,
  the/DT
  warm/JJ
  heart/NN
  beneath/NN
  ,/,
  The/DT
  simple/JJ
  grandeur/NN
  of/IN
  thy/JJ
  life/NN
  and/CC
  death/NN
  ./.
  F./NNP
  B./NNP
  SANBORN/NNP
  ./.
  April/NNP
  ,/,
  1857/CD
  ./.
  (ORGANIZATION SAMUEL/NNP)
  HOAR/NNP
  ./.
  HERE/NNP
  is/VBZ
  a/DT
  day/NN
  on/IN
  which/WDT
  more/RBR
  public/JJ
  good/JJ
  or/CC
  evil/JJ
  is/VBZ
  to/TO
  be/VB
  done/VBN
  than/IN
  was/VBD
  ever/RB
  done/VBN
  on/IN
  any/DT
  day/NN
  ./.
  And/CC
  this/DT
  is/VBZ
  the/DT
  pregnant/JJ
  season/NN
  ,/,
  when/WRB
  our/PRP$
  old/JJ
  (PERSON Roman/NNP)
  ,/,
  (PERSON Samuel/NNP Hoar/NNP)
  ,/,
  has/VBZ
  chosen/VBN
  to/TO
  quit/VB
  this/DT
  world/NN
  ./.
  Ab/NNP
  iniquo/JJ
  certamine/NN
  indignabundus/NN
  recessit/NN
  ./.
  He/PRP
  was/VBD
  born/VBN
  under/IN
  a/DT
  (GPE Christian/JJ)
  and/CC
  humane/JJ
  star/NN
  ,/,
  full/JJ
  of/IN
  mansuetude/NN
  and/CC
  nobleness/NN
  ,/,
  honour/NN
  and/CC
  charity/NN
  ;/:
  and/CC
  ,/,
  whilst/VBD
  he/PRP
  was/VBD
  willing/JJ
  to/TO
  face/VB
  every/DT
  disagreeable/JJ
  duty/NN
  ,/,
  whilst/NN
  he/PRP
  dared/VBD
  to/TO
  do/VB
  all/DT
  that/WDT
  might/MD
  beseem/VB
  a/DT
  man/NN
  ,/,
  his/PRP$
  self/NN
  respect/NN
  restrained/VBD
  him/PRP
  from/IN
  any/DT
  foolhardiness/NN
  ./.
  The/DT
  (ORGANIZATION Homeric/NNP)
  heroes/NNS
  ,/,
  when/WRB
  they/PRP
  saw/VBD
  the/DT
  gods/NNS
  mingling/VBG
  in/IN
  the/DT
  fray/NN
  ,/,
  sheathed/VBD
  their/PRP$
  swords/NNS
  ./.
  So/RB
  did/VBD
  not/RB
  he/PRP
  feel/VB
  any/DT
  call/NN
  to/TO
  make/VB
  it/PRP
  a/DT
  contest/NN
  of/IN
  personal/JJ
  strength/NN
  with/IN
  mobs/NN
  or/CC
  nations/NNS
  ;/:
  but/CC
  when/WRB
  he/PRP
  saw/VBD
  the/DT
  day/NN
  and/CC
  the/DT
  gods/NNS
  went/VBD
  against/IN
  him/PRP
  ,/,
  he/PRP
  withdrew/VBD
  ,/,
  but/CC
  with/IN
  an/DT
  unaltered/JJ
  belief/NN
  ./.
  All/DT
  was/VBD
  conquered/VBN
  prœter/NN
  atrocem/NN
  animum/JJ
  Catonis/NNP
  ./.
  At/IN
  the/DT
  time/NN
  when/WRB
  he/PRP
  went/VBD
  to/TO
  (GPE South/NNP Carolina/NNP)
  as/IN
  the/DT
  (ORGANIZATION Commissioner/NNP)
  of/IN
  (GPE Massachusetts/NNP)
  ,/,
  in/IN
  1844/CD
  ,/,
  whilst/VBD
  staying/VBG
  in/IN
  (GPE Charleston/NNP)
  ,/,
  pending/VBG
  his/PRP$
  correspondence/NN
  with/IN
  the/DT
  governor/NN
  and/CC
  the/DT
  legal/JJ
  officers/NNS
  ,/,
  he/PRP
  was/VBD
  repeatedly/RB
  warned/VBN
  that/IN
  it/PRP
  was/VBD
  not/RB
  safe/JJ
  for/IN
  him/PRP
  to/TO
  appear/VB
  in/IN
  public/JJ
  ,/,
  or/CC
  to/TO
  take/VB
  his/PRP$
  daily/JJ
  walk/NN
  ,/,
  as/IN
  he/PRP
  had/VBD
  done/VBN
  ,/,
  unattended/VBN
  by/IN
  his/PRP$
  friends/NNS
  ,/,
  in/IN
  the/DT
  streets/NNS
  of/IN
  the/DT
  city/NN
  ./.
  He/PRP
  was/VBD
  advised/VBN
  to/TO
  withdraw/VB
  to/TO
  private/JJ
  lodgings/NNS
  ,/,
  which/WDT
  were/VBD
  eagerly/RB
  offered/VBN
  him/PRP
  by/IN
  friends/NNS
  ./.
  He/PRP
  rejected/VBD
  the/DT
  advice/NN
  ,/,
  and/CC
  refused/VBD
  the/DT
  offers/NNS
  ,/,
  saying/VBG
  that/IN
  he/PRP
  was/VBD
  old/JJ
  ,/,
  and/CC
  his/PRP$
  life/NN
  was/VBD
  not/RB
  worth/JJ
  much/RB
  ,/,
  but/CC
  he/PRP
  had/VBD
  rather/RB
  the/DT
  boys/NNS
  should/MD
  troll/VB
  his/PRP$
  old/JJ
  head/NN
  like/IN
  a/DT
  football/NN
  in/IN
  their/PRP$
  streets/NNS
  ,/,
  than/IN
  that/IN
  he/PRP
  should/MD
  hide/VB
  it/PRP
  ./.
  And/CC
  he/PRP
  continued/VBD
  the/DT
  uniform/JJ
  practice/NN
  of/IN
  his/PRP$
  daily/JJ
  walk/NN
  into/IN
  all/DT
  parts/NNS
  of/IN
  the/DT
  city/NN
  ./.
  But/CC
  when/WRB
  the/DT
  mob/NN
  of/IN
  (PERSON Charleston/NNP)
  was/VBD
  assembled/VBN
  in/IN
  the/DT
  streets/NNS
  before/IN
  his/PRP$
  hotel/NN
  ,/,
  and/CC
  a/DT
  deputation/NN
  of/IN
  gentlemen/NNS
  waited/VBN
  upon/IN
  him/PRP
  in/IN
  the/DT
  hall/NN
  to/TO
  say/VB
  they/PRP
  had/VBD
  come/VBN
  with/IN
  the/DT
  unanimous/JJ
  voice/NN
  of/IN
  the/DT
  State/NNP
  to/TO
  remove/VB
  him/PRP
  by/IN
  force/NN
  ,/,
  and/CC
  the/DT
  carriage/NN
  was/VBD
  at/IN
  the/DT
  door/NN
  ,/,
  he/PRP
  considered/VBD
  his/PRP$
  duty/NN
  discharged/VBD
  to/TO
  the/DT
  last/JJ
  point/NN
  of/IN
  possibility/NN
  ./.
  The/DT
  force/NN
  was/VBD
  apparent/JJ
  and/CC
  irresistible/JJ
  ;/:
  the/DT
  legal/JJ
  officer/NN
  's/POS
  part/NN
  was/VBD
  up/RB
  ;/:
  it/PRP
  was/VBD
  now/RB
  time/NN
  for/IN
  the/DT
  military/JJ
  officer/NN
  to/TO
  be/VB
  sent/VBN
  ;/:
  and/CC
  he/PRP
  said/VBD
  ,/,
  “/NNP
  Well/NNP
  ,/,
  gentlemen/NNS
  ,/,
  since/IN
  it/PRP
  is/VBZ
  your/PRP$
  pleasure/NN
  to/TO
  use/VB
  force/NN
  ,/,
  I/PRP
  must/MD
  go./VB
  ”/NN
  But/CC
  his/PRP$
  opinion/NN
  was/VBD
  unchanged/JJ
  ./.
  In/IN
  like/JJ
  manner/NN
  now/RB
  ,/,
  when/WRB
  the/DT
  votes/NNS
  of/IN
  the/DT
  (GPE Free/NNP States/NNPS)
  ,/,
  as/IN
  shown/VBN
  in/IN
  the/DT
  recent/JJ
  election/NN
  in/IN
  the/DT
  State/NNP
  of/IN
  (GPE Pennsylvania/NNP)
  ,/,
  had/VBD
  disappointed/VBN
  the/DT
  hopes/NNS
  of/IN
  mankind/NN
  and/CC
  betrayed/VBD
  the/DT
  cause/NN
  of/IN
  freedom/NN
  ,/,
  he/PRP
  considered/VBD
  the/DT
  question/NN
  of/IN
  justice/NN
  and/CC
  liberty/NN
  ,/,
  for/IN
  his/PRP$
  age/NN
  ,/,
  lost/VBN
  ,/,
  and/CC
  had/VBD
  no/DT
  longer/RBR
  the/DT
  will/MD
  to/TO
  drag/VB
  his/PRP$
  days/NNS
  through/IN
  the/DT
  dishonours/NN
  of/IN
  the/DT
  long/JJ
  defeat/NN
  ,/,
  and/CC
  promptly/RB
  withdrew/VBD
  ,/,
  but/CC
  with/IN
  unaltered/JJ
  belief/NN
  ./.
  He/PRP
  was/VBD
  a/DT
  very/RB
  natural/JJ
  ,/,
  but/CC
  a/DT
  very/RB
  high/JJ
  character/NN
  ;/:
  a/DT
  man/NN
  of/IN
  simple/JJ
  tastes/NNS
  ,/,
  plain/NN
  and/CC
  true/JJ
  in/IN
  speech/NN
  ,/,
  with/IN
  a/DT
  clear/JJ
  perception/NN
  of/IN
  justice/NN
  ,/,
  and/CC
  a/DT
  perfect/JJ
  obedience/NN
  thereto/NN
  in/IN
  his/PRP$
  action/NN
  ;/:
  of/IN
  a/DT
  strong/JJ
  understanding/NN
  ,/,
  precise/NN
  and/CC
  methodical/NN
  ,/,
  which/WDT
  gave/VBD
  him/PRP
  great/JJ
  eminence/NN
  in/IN
  the/DT
  legal/JJ
  profession/NN
  ./.
  It/PRP
  was/VBD
  rather/RB
  his/PRP$
  reputation/NN
  for/IN
  severe/JJ
  method/NN
  in/IN
  his/PRP$
  intellect/NN
  than/IN
  any/DT
  special/JJ
  direction/NN
  in/IN
  his/PRP$
  studies/NNS
  that/WDT
  caused/VBD
  him/PRP
  to/TO
  be/VB
  offered/VBN
  the/DT
  mathematical/JJ
  chair/NN
  in/IN
  (ORGANIZATION Harvard/NNP University/NNP)
  ,/,
  when/WRB
  vacant/NN
  in/IN
  1806/CD
  ./.
  The/DT
  severity/NN
  of/IN
  his/PRP$
  logic/NN
  might/MD
  have/VB
  inspired/VBN
  fear/NN
  ,/,
  had/VBD
  it/PRP
  not/RB
  been/VBN
  restrained/VBN
  by/IN
  his/PRP$
  natural/JJ
  reverence/NN
  ,/,
  which/WDT
  made/VBD
  him/PRP
  modest/JJ
  and/CC
  courteous/JJ
  ,/,
  though/IN
  his/PRP$
  courtesy/NN
  had/VBD
  a/DT
  grave/NN
  and/CC
  almost/RB
  military/JJ
  air/NN
  ./.
  He/PRP
  combined/VBD
  a/DT
  uniform/JJ
  self/NN
  respect/NN
  with/IN
  a/DT
  natural/JJ
  reverence/NN
  for/IN
  every/DT
  other/JJ
  man/NN
  ;/:
  so/CC
  that/IN
  it/PRP
  was/VBD
  perfectly/RB
  easy/JJ
  for/IN
  him/PRP
  to/TO
  associate/VB
  with/IN
  farmers/NNS
  ,/,
  and/CC
  with/IN
  plain/NN
  ,/,
  uneducated/JJ
  ,/,
  poor/JJ
  men/NNS
  ,/,
  and/CC
  he/PRP
  had/VBD
  a/DT
  strong/JJ
  ,/,
  unaffected/JJ
  interest/NN
  in/IN
  farms/NNS
  ,/,
  and/CC
  crops/NNS
  ,/,
  and/CC
  weathers/NNS
  ,/,
  and/CC
  the/DT
  common/JJ
  incidents/NNS
  of/IN
  rural/JJ
  life/NN
  ./.
  It/PRP
  was/VBD
  just/RB
  as/IN
  easy/JJ
  for/IN
  him/PRP
  to/TO
  meet/VB
  on/IN
  the/DT
  same/JJ
  floor/NN
  ,/,
  and/CC
  with/IN
  the/DT
  same/JJ
  plain/NN
  courtesy/NN
  ,/,
  men/NNS
  of/IN
  distinction/NN
  and/CC
  large/JJ
  ability/NN
  ./.
  He/PRP
  was/VBD
  fond/NN
  of/IN
  farms/NNS
  and/CC
  trees/NNS
  ,/,
  fond/NN
  of/IN
  birds/NNS
  ,/,
  and/CC
  attentive/JJ
  to/TO
  their/PRP$
  manners/NNS
  and/CC
  habits/NNS
  ;/:
  addicted/VBN
  to/TO
  long/VB
  and/CC
  retired/JJ
  walks/NNS
  ;/:
  temperate/VB
  to/TO
  asceticism/VB
  ,/,
  for/IN
  no/DT
  lesson/NN
  of/IN
  his/PRP$
  experience/NN
  was/VBD
  lost/VBN
  on/IN
  him/PRP
  ,/,
  and/CC
  his/PRP$
  self/NN
  command/NN
  was/VBD
  perfect/JJ
  ./.
  Though/IN
  rich/JJ
  ,/,
  of/IN
  a/DT
  plainness/NN
  and/CC
  almost/RB
  poverty/NN
  of/IN
  personal/JJ
  expenditure/NN
  ,/,
  yet/RB
  liberal/JJ
  of/IN
  his/PRP$
  money/NN
  to/TO
  any/DT
  worthy/JJ
  use/NN
  ,/,
  readily/RB
  lending/VBG
  it/PRP
  to/TO
  young/JJ
  men/NNS
  ,/,
  and/CC
  industrious/JJ
  men/NNS
  ,/,
  and/CC
  by/IN
  no/DT
  means/NNS
  eager/VBP
  to/TO
  reclaim/VB
  of/IN
  them/PRP
  either/CC
  the/DT
  interest/NN
  or/CC
  the/DT
  principal/NN
  ./.
  He/PRP
  was/VBD
  open/JJ
  handed/VBN
  to/TO
  every/DT
  charity/NN
  ,/,
  and/CC
  every/DT
  public/JJ
  claim/NN
  that/WDT
  had/VBD
  any/DT
  show/NN
  of/IN
  reason/NN
  in/IN
  it/PRP
  ./.
  When/WRB
  I/PRP
  talked/VBD
  with/IN
  him/PRP
  one/CD
  day/NN
  of/IN
  some/DT
  inequality/NN
  of/IN
  taxes/NNS
  in/IN
  the/DT
  town/NN
  ,/,
  he/PRP
  said/VBD
  it/PRP
  was/VBD
  his/PRP$
  practice/NN
  to/TO
  pay/VB
  whatever/WDT
  was/VBD
  demanded/VBN
  ;/:
  for/IN
  ,/,
  though/IN
  he/PRP
  might/MD
  think/VB
  the/DT
  taxation/NN
  large/JJ
  and/CC
  very/RB
  unequally/RB
  proportioned/VBN
  ,/,
  yet/RB
  he/PRP
  thought/VBD
  the/DT
  money/NN
  might/MD
  as/RB
  well/RB
  go/VB
  in/IN
  this/DT
  way/NN
  as/IN
  in/IN
  any/DT
  other/JJ
  ./.
  The/DT
  strength/NN
  and/CC
  the/DT
  beauty/NN
  of/IN
  the/DT
  man/NN
  lay/NN
  in/IN
  the/DT
  natural/JJ
  goodness/NN
  and/CC
  justice/NN
  of/IN
  his/PRP$
  mind/NN
  ,/,
  which/WDT
  ,/,
  in/IN
  manhood/NN
  and/CC
  in/IN
  old/JJ
  age/NN
  ,/,
  after/IN
  dealing/VBG
  all/PDT
  his/PRP$
  life/NN
  with/IN
  weighty/JJ
  private/JJ
  and/CC
  public/JJ
  interests/NNS
  ,/,
  left/VBD
  an/DT
  infantile/JJ
  innocence/NN
  ,/,
  of/IN
  which/WDT
  we/PRP
  have/VBP
  no/DT
  second/JJ
  or/CC
  third/JJ
  example/NN
  ,/,
  —/VB
  the/DT
  strength/NN
  of/IN
  a/DT
  chief/NN
  united/JJ
  to/TO
  the/DT
  modesty/NN
  of/IN
  a/DT
  child/NN
  ./.
  He/PRP
  returned/VBD
  from/IN
  courts/NNS
  or/CC
  congresses/NNS
  to/TO
  sit/VB
  down/RP
  ,/,
  with/IN
  unaltered/JJ
  humility/NN
  ,/,
  in/IN
  the/DT
  church/NN
  or/CC
  in/IN
  the/DT
  townhouse/NN
  ,/,
  on/IN
  the/DT
  plain/NN
  wooden/JJ
  bench/NN
  where/WRB
  honour/NN
  came/VBD
  and/CC
  sat/VBD
  down/RB
  beside/RB
  him/PRP
  ./.
  He/PRP
  was/VBD
  a/DT
  man/NN
  in/IN
  whom/WP
  so/RB
  rare/JJ
  a/DT
  spirit/NN
  of/IN
  justice/NN
  visibly/RB
  dwelled/VBD
  ,/,
  that/IN
  if/IN
  one/CD
  had/VBD
  met/VBN
  him/PRP
  in/IN
  a/DT
  cabin/NN
  or/CC
  in/IN
  a/DT
  forest/NN
  he/PRP
  must/MD
  still/RB
  seem/VB
  a/DT
  public/JJ
  man/NN
  ,/,
  answering/VBG
  as/IN
  sovereign/JJ
  state/NN
  to/TO
  sovereign/VB
  state/NN
  ;/:
  and/CC
  might/MD
  easily/RB
  suggest/VB
  (PERSON Milton/NNP)
  's/POS
  picture/NN
  of/IN
  (PERSON John/NNP Bradshaw/NNP)
  ,/,
  that/WDT
  “/VBD
  he/PRP
  was/VBD
  a/DT
  consul/NN
  from/IN
  whom/WP
  the/DT
  fasces/NNS
  did/VBD
  not/RB
  depart/VB
  with/IN
  the/DT
  year/NN
  ,/,
  but/CC
  in/IN
  private/JJ
  seemed/VBD
  ever/RB
  sitting/VBG
  in/IN
  judgement/NN
  on/IN
  kings./NN
  ”/NN
  Everybody/NNP
  knew/VBD
  where/WRB
  to/TO
  find/VB
  him/PRP
  ./.
  What/WP
  he/PRP
  said/VBD
  ,/,
  that/WDT
  would/MD
  he/PRP
  do/VB
  ./.
  But/CC
  he/PRP
  disdained/VBD
  any/DT
  arts/NNS
  in/IN
  his/PRP$
  speech/NN
  :/:
  he/PRP
  was/VBD
  not/RB
  adorned/VBN
  with/IN
  any/DT
  graces/NNS
  of/IN
  rhetoric/NN
  ,/,
  “/NN
  But/CC
  simple/JJ
  truth/NN
  his/PRP$
  utmost/JJ
  skill./NN
  ”/NNP
  So/NNP
  cautious/JJ
  was/VBD
  he/PRP
  ,/,
  and/CC
  tender/NN
  of/IN
  the/DT
  truth/NN
  ,/,
  that/IN
  he/PRP
  sometimes/RB
  wearied/VBD
  his/PRP$
  audience/NN
  with/IN
  the/DT
  pains/NNS
  he/PRP
  took/VBD
  to/TO
  qualify/VB
  and/CC
  verify/VB
  his/PRP$
  statements/NNS
  ,/,
  adding/VBG
  clause/NN
  on/IN
  clause/NN
  to/TO
  do/VB
  justice/NN
  to/TO
  all/DT
  his/PRP$
  conviction/NN
  ./.
  He/PRP
  had/VBD
  little/JJ
  or/CC
  no/DT
  power/NN
  of/IN
  generalisation/NN
  ./.
  But/CC
  a/DT
  plain/JJ
  way/NN
  he/PRP
  had/VBD
  of/IN
  putting/VBG
  his/PRP$
  statement/NN
  with/IN
  all/DT
  his/PRP$
  might/MD
  ,/,
  and/CC
  now/RB
  and/CC
  then/RB
  borrowing/VBG
  the/DT
  aid/NN
  of/IN
  a/DT
  good/JJ
  story/NN
  ,/,
  or/CC
  a/DT
  farmer/NN
  's/POS
  phrase/NN
  ,/,
  whose/WP$
  force/NN
  had/VBD
  imprinted/VBN
  it/PRP
  on/IN
  his/PRP$
  memory/NN
  ,/,
  and/CC
  ,/,
  by/IN
  the/DT
  same/JJ
  token/NN
  ,/,
  his/PRP$
  hearers/NNS
  were/VBD
  bound/VBN
  to/TO
  remember/VB
  his/PRP$
  point/NN
  ./.
  The/DT
  impression/NN
  he/PRP
  made/VBD
  on/IN
  juries/NNS
  was/VBD
  honourable/JJ
  to/TO
  him/PRP
  and/CC
  them/PRP
  ./.
  For/IN
  a/DT
  long/JJ
  term/NN
  of/IN
  years/NNS
  ,/,
  he/PRP
  was/VBD
  at/IN
  the/DT
  head/NN
  of/IN
  the/DT
  bar/NN
  in/IN
  (GPE Middlesex/NNP)
  ,/,
  practising/NN
  ,/,
  also/RB
  ,/,
  in/IN
  the/DT
  adjoining/NN
  counties/NNS
  ./.
  He/PRP
  had/VBD
  one/CD
  side/NN
  or/CC
  the/DT
  other/JJ
  of/IN
  every/DT
  important/JJ
  case/NN
  ,/,
  and/CC
  his/PRP$
  influence/NN
  was/VBD
  reckoned/VBN
  despotic/JJ
  ,/,
  and/CC
  sometimes/RB
  complained/VBD
  of/IN
  as/IN
  a/DT
  bar/NN
  to/TO
  public/JJ
  justice/NN
  ./.
  Many/JJ
  good/JJ
  stories/NNS
  are/VBP
  still/RB
  told/VBN
  of/IN
  the/DT
  perplexity/NN
  of/IN
  jurors/NNS
  who/WP
  found/VBD
  the/DT
  law/NN
  and/CC
  the/DT
  evidence/NN
  on/IN
  one/CD
  side/NN
  ,/,
  and/CC
  yet/RB
  (PERSON Squire/NNP Hoar/NNP)
  had/VBD
  said/VBD
  that/IN
  he/PRP
  believed/VBD
  ,/,
  on/IN
  his/PRP$
  conscience/NN
  ,/,
  his/PRP$
  client/NN
  entitled/VBD
  to/TO
  a/DT
  verdict/NN
  ./.
  And/CC
  what/WP
  (GPE Middlesex/NNP)
  jury/NN
  ,/,
  containing/VBG
  any/DT
  god/JJ
  fearing/VBG
  men/NNS
  in/IN
  it/PRP
  ,/,
  would/MD
  hazard/VB
  an/DT
  opinion/NN
  in/IN
  flat/JJ
  contradiction/NN
  to/TO
  what/WP
  (PERSON Squire/NNP Hoar/NNP)
  believed/VBD
  to/TO
  be/VB
  just/RB
  ?/.
  He/PRP
  was/VBD
  entitled/VBN
  to/TO
  this/DT
  respect/NN
  ;/:
  for/IN
  he/PRP
  discriminated/VBD
  in/IN
  the/DT
  business/NN
  that/WDT
  was/VBD
  brought/VBN
  to/TO
  him/PRP
  ,/,
  and/CC
  would/MD
  not/RB
  argue/VB
  a/DT
  rotten/JJ
  cause/NN
  ;/:
  and/CC
  he/PRP
  refused/VBD
  very/RB
  large/JJ
  sums/NNS
  offered/VBD
  him/PRP
  to/TO
  undertake/VB
  the/DT
  defence/NN
  of/IN
  criminal/JJ
  persons/NNS
  ./.
  His/PRP$
  character/NN
  made/VBD
  him/PRP
  the/DT
  conscience/NN
  of/IN
  the/DT
  community/NN
  in/IN
  which/WDT
  he/PRP
  lived/VBD
  ./.
  And/CC
  in/IN
  many/JJ
  a/DT
  town/NN
  it/PRP
  was/VBD
  asked/VBN
  ,/,
  “/VB
  What/WP
  does/VBZ
  (PERSON Squire/NNP Hoar/NNP)
  think/NN
  of/IN
  this/DT
  ?/.
  ”/NN
  and/CC
  in/IN
  political/JJ
  crises/NNS
  ,/,
  he/PRP
  was/VBD
  entreated/VBN
  to/TO
  write/VB
  a/DT
  few/JJ
  lines/NNS
  to/TO
  make/VB
  known/VBN
  to/TO
  good/JJ
  men/NNS
  in/IN
  (GPE Chelmsford/NNP)
  ,/,
  or/CC
  Marlborough/NNP
  ,/,
  or/CC
  (PERSON Shirley/NNP)
  ,/,
  what/WP
  that/IN
  opinion/NN
  was/VBD
  ./.
  I/PRP
  used/VBD
  to/TO
  feel/VB
  that/IN
  his/PRP$
  conscience/NN
  was/VBD
  a/DT
  kind/NN
  of/IN
  metre/NN
  of/IN
  the/DT
  degree/NN
  of/IN
  honesty/NN
  in/IN
  the/DT
  country/NN
  ,/,
  by/IN
  which/WDT
  on/IN
  each/DT
  occasion/NN
  it/PRP
  was/VBD
  tried/VBN
  ,/,
  and/CC
  sometimes/RB
  found/VBD
  wanting/VBG
  ./.
  I/PRP
  am/VBP
  sorry/JJ
  to/TO
  say/VB
  he/PRP
  could/MD
  not/RB
  be/VB
  elected/VBN
  to/TO
  (ORGANIZATION Congress/NNP)
  a/DT
  second/JJ
  time/NN
  from/IN
  (GPE Middlesex/NNP)
  ./.
  And/CC
  in/IN
  his/PRP$
  own/JJ
  town/NN
  ,/,
  if/IN
  some/DT
  important/JJ
  end/NN
  was/VBD
  to/TO
  be/VB
  gained/VBN
  ,/,
  —/PRP
  as/IN
  ,/,
  for/IN
  instance/NN
  ,/,
  when/WRB
  the/DT
  county/NN
  commissioners/NNS
  refused/VBD
  to/TO
  rebuild/VB
  the/DT
  burned/VBN
  courthouse/NN
  ,/,
  on/IN
  the/DT
  belief/NN
  that/IN
  the/DT
  courts/NNS
  would/MD
  be/VB
  transferred/VBN
  from/IN
  (GSP Concord/NNP)
  to/TO
  (GPE Lowell/NNP)
  ,/,
  —/NNP
  all/DT
  parties/NNS
  combined/VBN
  to/TO
  send/VB
  (PERSON Mr./NNP Hoar/NNP)
  to/TO
  the/DT
  (ORGANIZATION Legislature/NNP)
  ,/,
  where/WRB
  his/PRP$
  presence/NN
  and/CC
  speech/NN
  ,/,
  of/IN
  course/NN
  ,/,
  secured/VBD
  the/DT
  rebuilding/NN
  ;/:
  and/CC
  ,/,
  of/IN
  course/NN
  also/RB
  ,/,
  having/VBG
  answered/VBN
  our/PRP$
  end/NN
  ,/,
  we/PRP
  passed/VBD
  him/PRP
  by/IN
  and/CC
  elected/VBN
  somebody/NN
  else/RB
  at/IN
  the/DT
  next/JJ
  term/NN
  ./.
  His/PRP$
  head/NN
  ,/,
  with/IN
  singular/JJ
  grace/NN
  in/IN
  its/PRP$
  lines/NNS
  ,/,
  had/VBD
  a/DT
  resemblance/NN
  to/TO
  the/DT
  bust/NN
  of/IN
  (GPE Dante/NNP)
  ./.
  He/PRP
  retained/VBD
  to/TO
  the/DT
  last/JJ
  the/DT
  erectness/NN
  of/IN
  his/PRP$
  tall/NN
  but/CC
  slender/NN
  form/NN
  ,/,
  and/CC
  not/RB
  less/VB
  the/DT
  full/JJ
  strength/NN
  of/IN
  his/PRP$
  mind/NN
  ./.
  (PERSON Such/JJ)
  was/VBD
  ,/,
  in/IN
  old/JJ
  age/NN
  ,/,
  the/DT
  beauty/NN
  of/IN
  his/PRP$
  person/NN
  and/CC
  carriage/NN
  ,/,
  as/IN
  if/IN
  the/DT
  mind/NN
  radiated/VBD
  ,/,
  and/CC
  made/VBD
  the/DT
  same/JJ
  impression/NN
  of/IN
  probity/NN
  on/IN
  all/DT
  beholders/NNS
  ./.
  His/PRP$
  beauty/NN
  was/VBD
  pathetic/JJ
  and/CC
  touching/VBG
  in/IN
  these/DT
  latest/JJS
  days/NNS
  ,/,
  and/CC
  ,/,
  as/IN
  now/RB
  appears/VBZ
  ,/,
  it/PRP
  awakened/VBD
  a/DT
  certain/JJ
  tender/NN
  fear/NN
  in/IN
  all/DT
  who/WP
  saw/VBD
  him/PRP
  ,/,
  that/IN
  the/DT
  costly/JJ
  ornament/NN
  of/IN
  our/PRP$
  homes/NNS
  and/CC
  halls/NNS
  and/CC
  streets/NNS
  was/VBD
  speedily/RB
  to/TO
  be/VB
  removed/VBN
  ./.

In [16]:
#see tree
ne

Tree('S', [Tree('ORGANIZATION', [('SAMUEL', 'NNP')]), Tree('GPE', [('HOAR', 'NNP')]), ('.', '.'), ('“', 'VB'), Tree('PERSON', [('Magno', 'NNP')]), ('southeast', 'JJ'), ('judice', 'NN'), ('quisque', 'NN'), ('tuetur', 'NN'), (';', ':'), ('Victrix', 'NNP'), ('causa', 'VBP'), ('deis', 'NN'), ('placuit', 'NN'), ('sed', 'VBD'), ('victa', 'JJ'), ('Catoni.', 'NNP'), ('”', 'NN'), ('A', 'NNP'), ('YEAR', 'NN'), ('ago', 'RB'), (',', ','), ('how', 'WRB'), ('often', 'RB'), ('did', 'VBD'), ('we', 'PRP'), ('meet', 'VB'), ('Beneath', 'IN'), ('these', 'DT'), ('elms', 'NNS'), (',', ','), ('once', 'RB'), ('more', 'RBR'), ('in', 'IN'), ('sober', 'NNP'), ('bloom', 'NN'), (',', ','), Tree('PERSON', [('Thy', 'NNP')]), ('tall', 'NN'), (',', ','), ('sad', 'JJ'), ('figure', 'NN'), ('pacing', 'VBG'), ('down', 'RP'), ('the', 'DT'), ('street', 'NN'), (',', ','), ('And', 'CC'), ('now', 'RB'), ('the', 'DT'), ('robin', 'NN'), ('sings', 'NNS'), ('above', 'IN'), ('thy', 'JJ'), ('tomb', 'NN'), ('!', '.'), ('Thy', 'NNP'), ('name', 'NN'), ('on', 'IN'), ('other', 'JJ'), ('shores', 'NNS'), ('may', 'MD'), ('never', 'RB'), ('be', 'VB'), ('known', 'VBN'), (',', ','), ('Though', 'IN'), Tree('PERSON', [('Rome', 'NNP')]), ('austere', 'RB'), ('no', 'DT'), ('graver', 'NN'), ('consul', 'NN'), ('knew', 'VBD'), (',', ','), ('But', 'CC'), Tree('GPE', [('Massachusetts', 'NNP')]), ('her', 'PRP$'), ('true', 'JJ'), ('son', 'NN'), ('shall', 'MD'), ('own', 'VB'), (';', ':'), ('Out', 'NNP'), ('of', 'IN'), ('her', 'PRP$'), ('soil', 'NN'), ('thy', 'NN'), ('hardy', 'NN'), ('virtues', 'NNS'), ('grew', 'VBD'), ('.', '.'), ('She', 'PRP'), ('loves', 'VBZ'), ('the', 'DT'), ('man', 'NN'), ('that', 'WDT'), ('chose', 'VBD'), ('the', 'DT'), ('conquered', 'JJ'), ('cause', 'NN'), (',', ','), ('With', 'IN'), ('upright', 'JJ'), ('soul', 'NN'), ('that', 'WDT'), ('bowed', 'VBD'), ('to', 'TO'), ('God', 'NNP'), ('alone', 'RB'), (';', ':'), ('The', 'DT'), ('clean', 'JJ'), ('hands', 'NNS'), ('that', 'WDT'), ('upheld', 'VBD'), ('her', 'PRP'), ('equal', 'JJ'), ('laws', 'NNS'), (',', ','), ('The', 'DT'), ('old', 'JJ'), ('religion', 'NN'), ('never', 'RB'), ('to', 'TO'), ('be', 'VB'), ('outgrown', 'VBN'), (';', ':'), ('The', 'DT'), ('cold', 'JJ'), ('demeanour', 'NN'), (',', ','), ('the', 'DT'), ('warm', 'JJ'), ('heart', 'NN'), ('beneath', 'NN'), (',', ','), ('The', 'DT'), ('simple', 'JJ'), ('grandeur', 'NN'), ('of', 'IN'), ('thy', 'JJ'), ('life', 'NN'), ('and', 'CC'), ('death', 'NN'), ('.', '.'), ('F.', 'NNP'), ('B.', 'NNP'), ('SANBORN', 'NNP'), ('.', '.'), ('April', 'NNP'), (',', ','), ('1857', 'CD'), ('.', '.'), Tree('ORGANIZATION', [('SAMUEL', 'NNP')]), ('HOAR', 'NNP'), ('.', '.'), ('HERE', 'NNP'), ('is', 'VBZ'), ('a', 'DT'), ('day', 'NN'), ('on', 'IN'), ('which', 'WDT'), ('more', 'RBR'), ('public', 'JJ'), ('good', 'JJ'), ('or', 'CC'), ('evil', 'JJ'), ('is', 'VBZ'), ('to', 'TO'), ('be', 'VB'), ('done', 'VBN'), ('than', 'IN'), ('was', 'VBD'), ('ever', 'RB'), ('done', 'VBN'), ('on', 'IN'), ('any', 'DT'), ('day', 'NN'), ('.', '.'), ('And', 'CC'), ('this', 'DT'), ('is', 'VBZ'), ('the', 'DT'), ('pregnant', 'JJ'), ('season', 'NN'), (',', ','), ('when', 'WRB'), ('our', 'PRP$'), ('old', 'JJ'), Tree('PERSON', [('Roman', 'NNP')]), (',', ','), Tree('PERSON', [('Samuel', 'NNP'), ('Hoar', 'NNP')]), (',', ','), ('has', 'VBZ'), ('chosen', 'VBN'), ('to', 'TO'), ('quit', 'VB'), ('this', 'DT'), ('world', 'NN'), ('.', '.'), ('Ab', 'NNP'), ('iniquo', 'JJ'), ('certamine', 'NN'), ('indignabundus', 'NN'), ('recessit', 'NN'), ('.', '.'), ('He', 'PRP'), ('was', 'VBD'), ('born', 'VBN'), ('under', 'IN'), ('a', 'DT'), Tree('GPE', [('Christian', 'JJ')]), ('and', 'CC'), ('humane', 'JJ'), ('star', 'NN'), (',', ','), ('full', 'JJ'), ('of', 'IN'), ('mansuetude', 'NN'), ('and', 'CC'), ('nobleness', 'NN'), (',', ','), ('honour', 'NN'), ('and', 'CC'), ('charity', 'NN'), (';', ':'), ('and', 'CC'), (',', ','), ('whilst', 'VBD'), ('he', 'PRP'), ('was', 'VBD'), ('willing', 'JJ'), ('to', 'TO'), ('face', 'VB'), ('every', 'DT'), ('disagreeable', 'JJ'), ('duty', 'NN'), (',', ','), ('whilst', 'NN'), ('he', 'PRP'), ('dared', 'VBD'), ('to', 'TO'), ('do', 'VB'), ('all', 'DT'), ('that', 'WDT'), ('might', 'MD'), ('beseem', 'VB'), ('a', 'DT'), ('man', 'NN'), (',', ','), ('his', 'PRP$'), ('self', 'NN'), ('respect', 'NN'), ('restrained', 'VBD'), ('him', 'PRP'), ('from', 'IN'), ('any', 'DT'), ('foolhardiness', 'NN'), ('.', '.'), ('The', 'DT'), Tree('ORGANIZATION', [('Homeric', 'NNP')]), ('heroes', 'NNS'), (',', ','), ('when', 'WRB'), ('they', 'PRP'), ('saw', 'VBD'), ('the', 'DT'), ('gods', 'NNS'), ('mingling', 'VBG'), ('in', 'IN'), ('the', 'DT'), ('fray', 'NN'), (',', ','), ('sheathed', 'VBD'), ('their', 'PRP$'), ('swords', 'NNS'), ('.', '.'), ('So', 'RB'), ('did', 'VBD'), ('not', 'RB'), ('he', 'PRP'), ('feel', 'VB'), ('any', 'DT'), ('call', 'NN'), ('to', 'TO'), ('make', 'VB'), ('it', 'PRP'), ('a', 'DT'), ('contest', 'NN'), ('of', 'IN'), ('personal', 'JJ'), ('strength', 'NN'), ('with', 'IN'), ('mobs', 'NN'), ('or', 'CC'), ('nations', 'NNS'), (';', ':'), ('but', 'CC'), ('when', 'WRB'), ('he', 'PRP'), ('saw', 'VBD'), ('the', 'DT'), ('day', 'NN'), ('and', 'CC'), ('the', 'DT'), ('gods', 'NNS'), ('went', 'VBD'), ('against', 'IN'), ('him', 'PRP'), (',', ','), ('he', 'PRP'), ('withdrew', 'VBD'), (',', ','), ('but', 'CC'), ('with', 'IN'), ('an', 'DT'), ('unaltered', 'JJ'), ('belief', 'NN'), ('.', '.'), ('All', 'DT'), ('was', 'VBD'), ('conquered', 'VBN'), ('prœter', 'NN'), ('atrocem', 'NN'), ('animum', 'JJ'), ('Catonis', 'NNP'), ('.', '.'), ('At', 'IN'), ('the', 'DT'), ('time', 'NN'), ('when', 'WRB'), ('he', 'PRP'), ('went', 'VBD'), ('to', 'TO'), Tree('GPE', [('South', 'NNP'), ('Carolina', 'NNP')]), ('as', 'IN'), ('the', 'DT'), Tree('ORGANIZATION', [('Commissioner', 'NNP')]), ('of', 'IN'), Tree('GPE', [('Massachusetts', 'NNP')]), (',', ','), ('in', 'IN'), ('1844', 'CD'), (',', ','), ('whilst', 'VBD'), ('staying', 'VBG'), ('in', 'IN'), Tree('GPE', [('Charleston', 'NNP')]), (',', ','), ('pending', 'VBG'), ('his', 'PRP$'), ('correspondence', 'NN'), ('with', 'IN'), ('the', 'DT'), ('governor', 'NN'), ('and', 'CC'), ('the', 'DT'), ('legal', 'JJ'), ('officers', 'NNS'), (',', ','), ('he', 'PRP'), ('was', 'VBD'), ('repeatedly', 'RB'), ('warned', 'VBN'), ('that', 'IN'), ('it', 'PRP'), ('was', 'VBD'), ('not', 'RB'), ('safe', 'JJ'), ('for', 'IN'), ('him', 'PRP'), ('to', 'TO'), ('appear', 'VB'), ('in', 'IN'), ('public', 'JJ'), (',', ','), ('or', 'CC'), ('to', 'TO'), ('take', 'VB'), ('his', 'PRP$'), ('daily', 'JJ'), ('walk', 'NN'), (',', ','), ('as', 'IN'), ('he', 'PRP'), ('had', 'VBD'), ('done', 'VBN'), (',', ','), ('unattended', 'VBN'), ('by', 'IN'), ('his', 'PRP$'), ('friends', 'NNS'), (',', ','), ('in', 'IN'), ('the', 'DT'), ('streets', 'NNS'), ('of', 'IN'), ('the', 'DT'), ('city', 'NN'), ('.', '.'), ('He', 'PRP'), ('was', 'VBD'), ('advised', 'VBN'), ('to', 'TO'), ('withdraw', 'VB'), ('to', 'TO'), ('private', 'JJ'), ('lodgings', 'NNS'), (',', ','), ('which', 'WDT'), ('were', 'VBD'), ('eagerly', 'RB'), ('offered', 'VBN'), ('him', 'PRP'), ('by', 'IN'), ('friends', 'NNS'), ('.', '.'), ('He', 'PRP'), ('rejected', 'VBD'), ('the', 'DT'), ('advice', 'NN'), (',', ','), ('and', 'CC'), ('refused', 'VBD'), ('the', 'DT'), ('offers', 'NNS'), (',', ','), ('saying', 'VBG'), ('that', 'IN'), ('he', 'PRP'), ('was', 'VBD'), ('old', 'JJ'), (',', ','), ('and', 'CC'), ('his', 'PRP$'), ('life', 'NN'), ('was', 'VBD'), ('not', 'RB'), ('worth', 'JJ'), ('much', 'RB'), (',', ','), ('but', 'CC'), ('he', 'PRP'), ('had', 'VBD'), ('rather', 'RB'), ('the', 'DT'), ('boys', 'NNS'), ('should', 'MD'), ('troll', 'VB'), ('his', 'PRP$'), ('old', 'JJ'), ('head', 'NN'), ('like', 'IN'), ('a', 'DT'), ('football', 'NN'), ('in', 'IN'), ('their', 'PRP$'), ('streets', 'NNS'), (',', ','), ('than', 'IN'), ('that', 'IN'), ('he', 'PRP'), ('should', 'MD'), ('hide', 'VB'), ('it', 'PRP'), ('.', '.'), ('And', 'CC'), ('he', 'PRP'), ('continued', 'VBD'), ('the', 'DT'), ('uniform', 'JJ'), ('practice', 'NN'), ('of', 'IN'), ('his', 'PRP$'), ('daily', 'JJ'), ('walk', 'NN'), ('into', 'IN'), ('all', 'DT'), ('parts', 'NNS'), ('of', 'IN'), ('the', 'DT'), ('city', 'NN'), ('.', '.'), ('But', 'CC'), ('when', 'WRB'), ('the', 'DT'), ('mob', 'NN'), ('of', 'IN'), Tree('PERSON', [('Charleston', 'NNP')]), ('was', 'VBD'), ('assembled', 'VBN'), ('in', 'IN'), ('the', 'DT'), ('streets', 'NNS'), ('before', 'IN'), ('his', 'PRP$'), ('hotel', 'NN'), (',', ','), ('and', 'CC'), ('a', 'DT'), ('deputation', 'NN'), ('of', 'IN'), ('gentlemen', 'NNS'), ('waited', 'VBN'), ('upon', 'IN'), ('him', 'PRP'), ('in', 'IN'), ('the', 'DT'), ('hall', 'NN'), ('to', 'TO'), ('say', 'VB'), ('they', 'PRP'), ('had', 'VBD'), ('come', 'VBN'), ('with', 'IN'), ('the', 'DT'), ('unanimous', 'JJ'), ('voice', 'NN'), ('of', 'IN'), ('the', 'DT'), ('State', 'NNP'), ('to', 'TO'), ('remove', 'VB'), ('him', 'PRP'), ('by', 'IN'), ('force', 'NN'), (',', ','), ('and', 'CC'), ('the', 'DT'), ('carriage', 'NN'), ('was', 'VBD'), ('at', 'IN'), ('the', 'DT'), ('door', 'NN'), (',', ','), ('he', 'PRP'), ('considered', 'VBD'), ('his', 'PRP$'), ('duty', 'NN'), ('discharged', 'VBD'), ('to', 'TO'), ('the', 'DT'), ('last', 'JJ'), ('point', 'NN'), ('of', 'IN'), ('possibility', 'NN'), ('.', '.'), ('The', 'DT'), ('force', 'NN'), ('was', 'VBD'), ('apparent', 'JJ'), ('and', 'CC'), ('irresistible', 'JJ'), (';', ':'), ('the', 'DT'), ('legal', 'JJ'), ('officer', 'NN'), ("'s", 'POS'), ('part', 'NN'), ('was', 'VBD'), ('up', 'RB'), (';', ':'), ('it', 'PRP'), ('was', 'VBD'), ('now', 'RB'), ('time', 'NN'), ('for', 'IN'), ('the', 'DT'), ('military', 'JJ'), ('officer', 'NN'), ('to', 'TO'), ('be', 'VB'), ('sent', 'VBN'), (';', ':'), ('and', 'CC'), ('he', 'PRP'), ('said', 'VBD'), (',', ','), ('“', 'NNP'), ('Well', 'NNP'), (',', ','), ('gentlemen', 'NNS'), (',', ','), ('since', 'IN'), ('it', 'PRP'), ('is', 'VBZ'), ('your', 'PRP$'), ('pleasure', 'NN'), ('to', 'TO'), ('use', 'VB'), ('force', 'NN'), (',', ','), ('I', 'PRP'), ('must', 'MD'), ('go.', 'VB'), ('”', 'NN'), ('But', 'CC'), ('his', 'PRP$'), ('opinion', 'NN'), ('was', 'VBD'), ('unchanged', 'JJ'), ('.', '.'), ('In', 'IN'), ('like', 'JJ'), ('manner', 'NN'), ('now', 'RB'), (',', ','), ('when', 'WRB'), ('the', 'DT'), ('votes', 'NNS'), ('of', 'IN'), ('the', 'DT'), Tree('GPE', [('Free', 'NNP'), ('States', 'NNPS')]), (',', ','), ('as', 'IN'), ('shown', 'VBN'), ('in', 'IN'), ('the', 'DT'), ('recent', 'JJ'), ('election', 'NN'), ('in', 'IN'), ('the', 'DT'), ('State', 'NNP'), ('of', 'IN'), Tree('GPE', [('Pennsylvania', 'NNP')]), (',', ','), ('had', 'VBD'), ('disappointed', 'VBN'), ('the', 'DT'), ('hopes', 'NNS'), ('of', 'IN'), ('mankind', 'NN'), ('and', 'CC'), ('betrayed', 'VBD'), ('the', 'DT'), ('cause', 'NN'), ('of', 'IN'), ('freedom', 'NN'), (',', ','), ('he', 'PRP'), ('considered', 'VBD'), ('the', 'DT'), ('question', 'NN'), ('of', 'IN'), ('justice', 'NN'), ('and', 'CC'), ('liberty', 'NN'), (',', ','), ('for', 'IN'), ('his', 'PRP$'), ('age', 'NN'), (',', ','), ('lost', 'VBN'), (',', ','), ('and', 'CC'), ('had', 'VBD'), ('no', 'DT'), ('longer', 'RBR'), ('the', 'DT'), ('will', 'MD'), ('to', 'TO'), ('drag', 'VB'), ('his', 'PRP$'), ('days', 'NNS'), ('through', 'IN'), ('the', 'DT'), ('dishonours', 'NN'), ('of', 'IN'), ('the', 'DT'), ('long', 'JJ'), ('defeat', 'NN'), (',', ','), ('and', 'CC'), ('promptly', 'RB'), ('withdrew', 'VBD'), (',', ','), ('but', 'CC'), ('with', 'IN'), ('unaltered', 'JJ'), ('belief', 'NN'), ('.', '.'), ('He', 'PRP'), ('was', 'VBD'), ('a', 'DT'), ('very', 'RB'), ('natural', 'JJ'), (',', ','), ('but', 'CC'), ('a', 'DT'), ('very', 'RB'), ('high', 'JJ'), ('character', 'NN'), (';', ':'), ('a', 'DT'), ('man', 'NN'), ('of', 'IN'), ('simple', 'JJ'), ('tastes', 'NNS'), (',', ','), ('plain', 'NN'), ('and', 'CC'), ('true', 'JJ'), ('in', 'IN'), ('speech', 'NN'), (',', ','), ('with', 'IN'), ('a', 'DT'), ('clear', 'JJ'), ('perception', 'NN'), ('of', 'IN'), ('justice', 'NN'), (',', ','), ('and', 'CC'), ('a', 'DT'), ('perfect', 'JJ'), ('obedience', 'NN'), ('thereto', 'NN'), ('in', 'IN'), ('his', 'PRP$'), ('action', 'NN'), (';', ':'), ('of', 'IN'), ('a', 'DT'), ('strong', 'JJ'), ('understanding', 'NN'), (',', ','), ('precise', 'NN'), ('and', 'CC'), ('methodical', 'NN'), (',', ','), ('which', 'WDT'), ('gave', 'VBD'), ('him', 'PRP'), ('great', 'JJ'), ('eminence', 'NN'), ('in', 'IN'), ('the', 'DT'), ('legal', 'JJ'), ('profession', 'NN'), ('.', '.'), ('It', 'PRP'), ('was', 'VBD'), ('rather', 'RB'), ('his', 'PRP$'), ('reputation', 'NN'), ('for', 'IN'), ('severe', 'JJ'), ('method', 'NN'), ('in', 'IN'), ('his', 'PRP$'), ('intellect', 'NN'), ('than', 'IN'), ('any', 'DT'), ('special', 'JJ'), ('direction', 'NN'), ('in', 'IN'), ('his', 'PRP$'), ('studies', 'NNS'), ('that', 'WDT'), ('caused', 'VBD'), ('him', 'PRP'), ('to', 'TO'), ('be', 'VB'), ('offered', 'VBN'), ('the', 'DT'), ('mathematical', 'JJ'), ('chair', 'NN'), ('in', 'IN'), Tree('ORGANIZATION', [('Harvard', 'NNP'), ('University', 'NNP')]), (',', ','), ('when', 'WRB'), ('vacant', 'NN'), ('in', 'IN'), ('1806', 'CD'), ('.', '.'), ('The', 'DT'), ('severity', 'NN'), ('of', 'IN'), ('his', 'PRP$'), ('logic', 'NN'), ('might', 'MD'), ('have', 'VB'), ('inspired', 'VBN'), ('fear', 'NN'), (',', ','), ('had', 'VBD'), ('it', 'PRP'), ('not', 'RB'), ('been', 'VBN'), ('restrained', 'VBN'), ('by', 'IN'), ('his', 'PRP$'), ('natural', 'JJ'), ('reverence', 'NN'), (',', ','), ('which', 'WDT'), ('made', 'VBD'), ('him', 'PRP'), ('modest', 'JJ'), ('and', 'CC'), ('courteous', 'JJ'), (',', ','), ('though', 'IN'), ('his', 'PRP$'), ('courtesy', 'NN'), ('had', 'VBD'), ('a', 'DT'), ('grave', 'NN'), ('and', 'CC'), ('almost', 'RB'), ('military', 'JJ'), ('air', 'NN'), ('.', '.'), ('He', 'PRP'), ('combined', 'VBD'), ('a', 'DT'), ('uniform', 'JJ'), ('self', 'NN'), ('respect', 'NN'), ('with', 'IN'), ('a', 'DT'), ('natural', 'JJ'), ('reverence', 'NN'), ('for', 'IN'), ('every', 'DT'), ('other', 'JJ'), ('man', 'NN'), (';', ':'), ('so', 'CC'), ('that', 'IN'), ('it', 'PRP'), ('was', 'VBD'), ('perfectly', 'RB'), ('easy', 'JJ'), ('for', 'IN'), ('him', 'PRP'), ('to', 'TO'), ('associate', 'VB'), ('with', 'IN'), ('farmers', 'NNS'), (',', ','), ('and', 'CC'), ('with', 'IN'), ('plain', 'NN'), (',', ','), ('uneducated', 'JJ'), (',', ','), ('poor', 'JJ'), ('men', 'NNS'), (',', ','), ('and', 'CC'), ('he', 'PRP'), ('had', 'VBD'), ('a', 'DT'), ('strong', 'JJ'), (',', ','), ('unaffected', 'JJ'), ('interest', 'NN'), ('in', 'IN'), ('farms', 'NNS'), (',', ','), ('and', 'CC'), ('crops', 'NNS'), (',', ','), ('and', 'CC'), ('weathers', 'NNS'), (',', ','), ('and', 'CC'), ('the', 'DT'), ('common', 'JJ'), ('incidents', 'NNS'), ('of', 'IN'), ('rural', 'JJ'), ('life', 'NN'), ('.', '.'), ('It', 'PRP'), ('was', 'VBD'), ('just', 'RB'), ('as', 'IN'), ('easy', 'JJ'), ('for', 'IN'), ('him', 'PRP'), ('to', 'TO'), ('meet', 'VB'), ('on', 'IN'), ('the', 'DT'), ('same', 'JJ'), ('floor', 'NN'), (',', ','), ('and', 'CC'), ('with', 'IN'), ('the', 'DT'), ('same', 'JJ'), ('plain', 'NN'), ('courtesy', 'NN'), (',', ','), ('men', 'NNS'), ('of', 'IN'), ('distinction', 'NN'), ('and', 'CC'), ('large', 'JJ'), ('ability', 'NN'), ('.', '.'), ('He', 'PRP'), ('was', 'VBD'), ('fond', 'NN'), ('of', 'IN'), ('farms', 'NNS'), ('and', 'CC'), ('trees', 'NNS'), (',', ','), ('fond', 'NN'), ('of', 'IN'), ('birds', 'NNS'), (',', ','), ('and', 'CC'), ('attentive', 'JJ'), ('to', 'TO'), ('their', 'PRP$'), ('manners', 'NNS'), ('and', 'CC'), ('habits', 'NNS'), (';', ':'), ('addicted', 'VBN'), ('to', 'TO'), ('long', 'VB'), ('and', 'CC'), ('retired', 'JJ'), ('walks', 'NNS'), (';', ':'), ('temperate', 'VB'), ('to', 'TO'), ('asceticism', 'VB'), (',', ','), ('for', 'IN'), ('no', 'DT'), ('lesson', 'NN'), ('of', 'IN'), ('his', 'PRP$'), ('experience', 'NN'), ('was', 'VBD'), ('lost', 'VBN'), ('on', 'IN'), ('him', 'PRP'), (',', ','), ('and', 'CC'), ('his', 'PRP$'), ('self', 'NN'), ('command', 'NN'), ('was', 'VBD'), ('perfect', 'JJ'), ('.', '.'), ('Though', 'IN'), ('rich', 'JJ'), (',', ','), ('of', 'IN'), ('a', 'DT'), ('plainness', 'NN'), ('and', 'CC'), ('almost', 'RB'), ('poverty', 'NN'), ('of', 'IN'), ('personal', 'JJ'), ('expenditure', 'NN'), (',', ','), ('yet', 'RB'), ('liberal', 'JJ'), ('of', 'IN'), ('his', 'PRP$'), ('money', 'NN'), ('to', 'TO'), ('any', 'DT'), ('worthy', 'JJ'), ('use', 'NN'), (',', ','), ('readily', 'RB'), ('lending', 'VBG'), ('it', 'PRP'), ('to', 'TO'), ('young', 'JJ'), ('men', 'NNS'), (',', ','), ('and', 'CC'), ('industrious', 'JJ'), ('men', 'NNS'), (',', ','), ('and', 'CC'), ('by', 'IN'), ('no', 'DT'), ('means', 'NNS'), ('eager', 'VBP'), ('to', 'TO'), ('reclaim', 'VB'), ('of', 'IN'), ('them', 'PRP'), ('either', 'CC'), ('the', 'DT'), ('interest', 'NN'), ('or', 'CC'), ('the', 'DT'), ('principal', 'NN'), ('.', '.'), ('He', 'PRP'), ('was', 'VBD'), ('open', 'JJ'), ('handed', 'VBN'), ('to', 'TO'), ('every', 'DT'), ('charity', 'NN'), (',', ','), ('and', 'CC'), ('every', 'DT'), ('public', 'JJ'), ('claim', 'NN'), ('that', 'WDT'), ('had', 'VBD'), ('any', 'DT'), ('show', 'NN'), ('of', 'IN'), ('reason', 'NN'), ('in', 'IN'), ('it', 'PRP'), ('.', '.'), ('When', 'WRB'), ('I', 'PRP'), ('talked', 'VBD'), ('with', 'IN'), ('him', 'PRP'), ('one', 'CD'), ('day', 'NN'), ('of', 'IN'), ('some', 'DT'), ('inequality', 'NN'), ('of', 'IN'), ('taxes', 'NNS'), ('in', 'IN'), ('the', 'DT'), ('town', 'NN'), (',', ','), ('he', 'PRP'), ('said', 'VBD'), ('it', 'PRP'), ('was', 'VBD'), ('his', 'PRP$'), ('practice', 'NN'), ('to', 'TO'), ('pay', 'VB'), ('whatever', 'WDT'), ('was', 'VBD'), ('demanded', 'VBN'), (';', ':'), ('for', 'IN'), (',', ','), ('though', 'IN'), ('he', 'PRP'), ('might', 'MD'), ('think', 'VB'), ('the', 'DT'), ('taxation', 'NN'), ('large', 'JJ'), ('and', 'CC'), ('very', 'RB'), ('unequally', 'RB'), ('proportioned', 'VBN'), (',', ','), ('yet', 'RB'), ('he', 'PRP'), ('thought', 'VBD'), ('the', 'DT'), ('money', 'NN'), ('might', 'MD'), ('as', 'RB'), ('well', 'RB'), ('go', 'VB'), ('in', 'IN'), ('this', 'DT'), ('way', 'NN'), ('as', 'IN'), ('in', 'IN'), ('any', 'DT'), ('other', 'JJ'), ('.', '.'), ('The', 'DT'), ('strength', 'NN'), ('and', 'CC'), ('the', 'DT'), ('beauty', 'NN'), ('of', 'IN'), ('the', 'DT'), ('man', 'NN'), ('lay', 'NN'), ('in', 'IN'), ('the', 'DT'), ('natural', 'JJ'), ('goodness', 'NN'), ('and', 'CC'), ('justice', 'NN'), ('of', 'IN'), ('his', 'PRP$'), ('mind', 'NN'), (',', ','), ('which', 'WDT'), (',', ','), ('in', 'IN'), ('manhood', 'NN'), ('and', 'CC'), ('in', 'IN'), ('old', 'JJ'), ('age', 'NN'), (',', ','), ('after', 'IN'), ('dealing', 'VBG'), ('all', 'PDT'), ('his', 'PRP$'), ('life', 'NN'), ('with', 'IN'), ('weighty', 'JJ'), ('private', 'JJ'), ('and', 'CC'), ('public', 'JJ'), ('interests', 'NNS'), (',', ','), ('left', 'VBD'), ('an', 'DT'), ('infantile', 'JJ'), ('innocence', 'NN'), (',', ','), ('of', 'IN'), ('which', 'WDT'), ('we', 'PRP'), ('have', 'VBP'), ('no', 'DT'), ('second', 'JJ'), ('or', 'CC'), ('third', 'JJ'), ('example', 'NN'), (',', ','), ('—', 'VB'), ('the', 'DT'), ('strength', 'NN'), ('of', 'IN'), ('a', 'DT'), ('chief', 'NN'), ('united', 'JJ'), ('to', 'TO'), ('the', 'DT'), ('modesty', 'NN'), ('of', 'IN'), ('a', 'DT'), ('child', 'NN'), ('.', '.'), ('He', 'PRP'), ('returned', 'VBD'), ('from', 'IN'), ('courts', 'NNS'), ('or', 'CC'), ('congresses', 'NNS'), ('to', 'TO'), ('sit', 'VB'), ('down', 'RP'), (',', ','), ('with', 'IN'), ('unaltered', 'JJ'), ('humility', 'NN'), (',', ','), ('in', 'IN'), ('the', 'DT'), ('church', 'NN'), ('or', 'CC'), ('in', 'IN'), ('the', 'DT'), ('townhouse', 'NN'), (',', ','), ('on', 'IN'), ('the', 'DT'), ('plain', 'NN'), ('wooden', 'JJ'), ('bench', 'NN'), ('where', 'WRB'), ('honour', 'NN'), ('came', 'VBD'), ('and', 'CC'), ('sat', 'VBD'), ('down', 'RB'), ('beside', 'RB'), ('him', 'PRP'), ('.', '.'), ('He', 'PRP'), ('was', 'VBD'), ('a', 'DT'), ('man', 'NN'), ('in', 'IN'), ('whom', 'WP'), ('so', 'RB'), ('rare', 'JJ'), ('a', 'DT'), ('spirit', 'NN'), ('of', 'IN'), ('justice', 'NN'), ('visibly', 'RB'), ('dwelled', 'VBD'), (',', ','), ('that', 'IN'), ('if', 'IN'), ('one', 'CD'), ('had', 'VBD'), ('met', 'VBN'), ('him', 'PRP'), ('in', 'IN'), ('a', 'DT'), ('cabin', 'NN'), ('or', 'CC'), ('in', 'IN'), ('a',

# Optional: convert pos data to dataframe

In [10]:
# can convert pos data to pandas dataframe for easier use. Harder to convert named entity data because only lines
# the process believes are named entities are tagged, leaving an uneven data structure pandas can't parse.
import pandas as pd
df = pd.DataFrame(pos)

In [12]:
df

            0     1
0      SAMUEL   NNP
1        HOAR   NNP
2           .     .
3           “    VB
4       Magno   NNP
...       ...   ...
3319       in    IN
3320      his  PRP$
3321  liberal    JJ
3322     hand    NN
3323        .     .

[3324 rows x 2 columns]

# Spacy Tagging
Spacy provides tagging and is a bit more interchangeable than NLTK

In [21]:
#spacy implementation of NER
!pip3 install spacy && python3 -m spacy download en_core_web_sm
import spacy 
nlp = spacy.load("en_core_web_sm")

Requirement already satisfied: spacy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (3.5.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (1.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (3.0.8)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (8.1.7)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (1.1.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (2.4.5)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (2.0.8)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (0.7.0)
Requirement already satisfied: pathy>=0.10.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (0.10.1)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (6.3.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (4.64.1)
Requirement already satisfied: numpy>=1.15.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (1.24.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (2.28.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (1.10.4)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (67.1.0)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (23.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy) (4.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.12.7)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.0.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from typer<0.8.0,>=0.3.0->spacy) (8.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2->spacy) (2.1.2)
Collecting en-core-web-sm==3.5.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 28.6 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: spacy<3.6.0,>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from en-core-web-sm==3.5.0) (3.5.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.8)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (8.1.7)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.1.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.4.5)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.0.8)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.7.0)
Requirement already satisfied: pathy>=0.10.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.10.1)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (6.3.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (4.64.1)
Requirement already satisfied: numpy>=1.15.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.24.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.28.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.10.4)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.1.2)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (67.1.0)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (23.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (4.4.0)

Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2022.12.7)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from thinc<8.2.0,>=8.1.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from thinc<8.2.0,>=8.1.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (0.0.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from typer<0.8.0,>=0.3.0->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (8.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2->spacy<3.6.0,>=3.5.0->en-core-web-sm==3.5.0) (2.1.2)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [23]:
# tag text with POS info
doc = nlp(corpus[0])
pos_output = []
for token in doc:
    pos_output.append(token.text + " " + token.tag_ + " " + token.pos_)

In [24]:
pos_output

['SAMUEL NNP PROPN',
 'HOAR NNP PROPN',
 '. . PUNCT',
 '\n\n _SP SPACE',
 '“ `` PUNCT',
 'Magno NNP PROPN',
 'southeast JJ ADJ',
 'judice NN NOUN',
 'quisque NN NOUN',
 'tuetur NN NOUN',
 '; : PUNCT',
 '\n\n _SP SPACE',
 'Victrix NNP PROPN',
 'causa NN NOUN',
 'deis NN NOUN',
 'placuit NN NOUN',
 'sed VBD VERB',
 'victa NNP PROPN',
 'Catoni NNP PROPN',
 '. . PUNCT',
 "” '' PUNCT",
 '\n\n\n\n\n\n _SP SPACE',
 'A DT DET',
 'YEAR NN NOUN',
 'ago RB ADV',
 ', , PUNCT',
 'how WRB SCONJ',
 'often RB ADV',
 'did VBD AUX',
 'we PRP PRON',
 'meet VB VERB',
 '\n\n _SP SPACE',
 'Beneath IN ADP',
 'these DT DET',
 'elms NNS NOUN',
 ', , PUNCT',
 'once RB ADV',
 'more JJR ADJ',
 'in IN ADP',
 'sober JJ ADJ',
 'bloom NN NOUN',
 ', , PUNCT',
 '\n\n _SP SPACE',
 'Thy VBD VERB',
 'tall JJ ADJ',
 ', , PUNCT',
 'sad JJ ADJ',
 'figure NN NOUN',
 'pacing VBG VERB',
 'down IN ADP',
 'the DT DET',
 'street NN NOUN',
 ', , PUNCT',
 '\n\n _SP SPACE',
 'And CC CCONJ',
 'now RB ADV',
 'the DT DET',
 'robin NN NOUN',
 'sings VBZ VERB',
 'above IN ADP',
 'thy PRP$ PRON',
 'tomb NN NOUN',
 '! . PUNCT',
 '\n\n _SP SPACE',
 'Thy VBN VERB',
 'name NN NOUN',
 'on IN ADP',
 'other JJ ADJ',
 'shores NNS NOUN',
 'may MD AUX',
 'never RB ADV',
 'be VB AUX',
 'known VBN VERB',
 ', , PUNCT',
 '\n\n _SP SPACE',
 'Though IN SCONJ',
 'Rome NNP PROPN',
 'austere VBP VERB',
 'no DT DET',
 'graver JJ ADJ',
 'consul NN NOUN',
 'knew VBD VERB',
 ', , PUNCT',
 '\n\n _SP SPACE',
 'But CC CCONJ',
 'Massachusetts NNP PROPN',
 'her PRP$ PRON',
 'true JJ ADJ',
 'son NN NOUN',
 'shall MD AUX',
 'own VB VERB',
 '; : PUNCT',
 '\n\n _SP SPACE',
 'Out IN ADP',
 'of IN ADP',
 'her PRP$ PRON',
 'soil NN NOUN',
 'thy PRP$ PRON',
 'hardy JJ ADJ',
 'virtues NNS NOUN',
 'grew VBD VERB',
 '. . PUNCT',
 '\n\n _SP SPACE',
 'She PRP PRON',
 'loves VBZ VERB',
 'the DT DET',
 'man NN NOUN',
 'that WDT PRON',
 'chose VBD VERB',
 'the DT DET',
 'conquered JJ ADJ',
 'cause NN NOUN',
 ', , PUNCT',
 '\n\n _SP SPACE',
 'With IN ADP',
 'upright JJ ADJ',
 'soul NN NOUN',
 'that WDT PRON',
 'bowed VBD VERB',
 'to IN ADP',
 'God NNP PROPN',
 'alone RB ADV',
 '; : PUNCT',
 '\n\n _SP SPACE',
 'The DT DET',
 'clean JJ ADJ',
 'hands NNS NOUN',
 'that WDT PRON',
 'upheld VBD VERB',
 'her PRP$ PRON',
 'equal JJ ADJ',
 'laws NNS NOUN',
 ', , PUNCT',
 '\n\n _SP SPACE',
 'The DT DET',
 'old JJ ADJ',
 'religion NN NOUN',
 'never RB ADV',
 'to TO PART',
 'be VB AUX',
 'outgrown VBN VERB',
 '; : PUNCT',
 '\n\n _SP SPACE',
 'The DT DET',
 'cold JJ ADJ',
 'demeanour NN NOUN',
 ', , PUNCT',
 'the DT DET',
 'warm JJ ADJ',
 'heart NN NOUN',
 'beneath IN ADP',
 ', , PUNCT',
 '\n\n _SP SPACE',
 'The DT DET',
 'simple JJ ADJ',
 'grandeur NN NOUN',
 'of IN ADP',
 'thy PRP$ PRON',
 'life NN NOUN',
 'and CC CCONJ',
 'death NN NOUN',
 '. . PUNCT',
 '\n\n _SP SPACE',
 'F. NNP PROPN',
 'B. NNP PROPN',
 'SANBORN NNP PROPN',
 '. . PUNCT',
 '\n\n _SP SPACE',
 'April NNP PROPN',
 ', , PUNCT',
 '1857 CD NUM',
 '. . PUNCT',
 '\n\n\n\n\n\n _SP SPACE',
 'SAMUEL NNP PROPN',
 'HOAR NNP PROPN',
 '. . PUNCT',
 '\n\n _SP SPACE',
 'HERE RB ADV',
 'is VBZ AUX',
 'a DT DET',
 'day NN NOUN',
 'on IN ADP',
 'which WDT PRON',
 'more JJR ADJ',
 'public JJ ADJ',
 'good NN NOUN',
 'or CC CCONJ',
 'evil NN NOUN',
 'is VBZ AUX',
 'to TO PART',
 'be VB AUX',
 'done VBN VERB',
 'than IN SCONJ',
 'was VBD AUX',
 'ever RB ADV',
 'done VBN VERB',
 'on IN ADP',
 'any DT DET',
 'day NN NOUN',
 '. . PUNCT',
 'And CC CCONJ',
 'this DT PRON',
 'is VBZ AUX',
 'the DT DET',
 'pregnant JJ ADJ',
 'season NN NOUN',
 ', , PUNCT',
 'when WRB SCONJ',
 'our PRP$ PRON',
 'old JJ ADJ',
 'Roman NNP PROPN',
 ', , PUNCT',
 'Samuel NNP PROPN',
 'Hoar NNP PROPN',
 ', , PUNCT',
 'has VBZ AUX',
 'chosen VBN VERB',
 'to TO PART',
 'quit VB VERB',
 'this DT DET',
 'world NN NOUN',
 '. . PUNCT',
 'Ab VB VERB',
 'iniquo NN NOUN',
 'certamine NNP PROPN',
 'indignabundus NNP PROPN',
 'recessit VB VERB',
 '. . PUNCT',
 '\n\n _SP SPACE',
 'He PRP PRON',
 'was VBD AUX',
 'born VBN VERB',
 'under IN ADP',
 'a DT DET',
 'Christian JJ ADJ',
 'and CC CCONJ',
 'humane JJ ADJ',
 'star NN NOUN',
 ', , PUNCT',
 'full JJ ADJ',
 'of IN ADP',
 'mansuetude NN NOUN',
 'and CC CCONJ',
 'nobleness NN NOUN',
 ', , PUNCT',
 'honour NN NOUN',
 'and CC CCONJ',
 'charity NN NOUN',
 '; : PUNCT',
 'and CC CCONJ',
 ', , PUNCT',
 'whilst IN SCONJ',
 'he PRP PRON',
 'was VBD AUX',
 'willing JJ ADJ',
 'to TO PART',
 'face VB VERB',
 'every DT DET',
 'disagreeable JJ ADJ',
 'duty NN NOUN',
 ', , PUNCT',
 'whilst IN SCONJ',
 'he PRP PRON',
 'dared VBD VERB',
 'to TO PART',
 'do VB VERB',
 'all DT PRON',
 'that WDT PRON',
 'might MD AUX',
 'beseem VB VERB',
 'a DT DET',
 'man NN NOUN',
 ', , PUNCT',
 'his PRP$ PRON',
 'self NN NOUN',
 'respect NN NOUN',
 'restrained VBD VERB',
 'him PRP PRON',
 'from IN ADP',
 'any DT DET',
 'foolhardiness NN NOUN',
 '. . PUNCT',
 'The DT DET',
 'Homeric NNP PROPN',
 'heroes NNS NOUN',
 ', , PUNCT',
 'when WRB SCONJ',
 'they PRP PRON',
 'saw VBD VERB',
 'the DT DET',
 'gods NNS NOUN',
 'mingling VBG VERB',
 'in IN ADP',
 'the DT DET',
 'fray NN NOUN',
 ', , PUNCT',
 'sheathed VBD VERB',
 'their PRP$ PRON',
 'swords NNS NOUN',
 '. . PUNCT',
 'So RB ADV',
 'did VBD AUX',
 'not RB PART',
 'he PRP PRON',
 'feel VB VERB',
 'any DT DET',
 'call NN NOUN',
 'to TO PART',
 'make VB VERB',
 'it PRP PRON',
 'a DT DET',
 'contest NN NOUN',
 'of IN ADP',
 'personal JJ ADJ',
 'strength NN NOUN',
 'with IN ADP',
 'mobs NNS NOUN',
 'or CC CCONJ',
 'nations NNS NOUN',
 '; : PUNCT',
 'but CC CCONJ',
 'when WRB SCONJ',
 'he PRP PRON',
 'saw VBD VERB',
 'the DT DET',
 'day NN NOUN',
 'and CC CCONJ',
 'the DT DET',
 'gods NNS NOUN',
 'went VBD VERB',
 'against IN ADP',
 'him PRP PRON',
 ', , PUNCT',
 'he PRP PRON',
 'withdrew VBD VERB',
 ', , PUNCT',
 'but CC CCONJ',
 'with IN ADP',
 'an DT DET',
 'unaltered JJ ADJ',
 'belief NN NOUN',
 '. . PUNCT',
 'All DT PRON',
 'was VBD AUX',
 'conquered VBN VERB',
 'prœter NN NOUN',
 'atrocem NNP PROPN',
 'animum JJ ADJ',
 'Catonis NNP PROPN',
 '. . PUNCT',
 '\n\n _SP SPACE',
 'At IN ADP',
 'the DT DET',
 'time NN NOUN',
 'when WRB SCONJ',
 'he PRP PRON',
 'went VBD VERB',
 'to IN ADP',
 'South NNP PROPN',
 'Carolina NNP PROPN',
 'as IN ADP',
 'the DT DET',
 'Commissioner NNP PROPN',
 'of IN ADP',
 'Massachusetts NNP PROPN',
 ', , PUNCT',
 'in IN ADP',
 '1844 CD NUM',
 ', , PUNCT',
 'whilst IN SCONJ',
 'staying VBG VERB',
 'in IN ADP',
 'Charleston NNP PROPN',
 ', , PUNCT',
 'pending VBG VERB',
 'his PRP$ PRON',
 'correspondence NN NOUN',
 'with IN ADP',
 'the DT DET',
 'governor NN NOUN',
 'and CC CCONJ',
 'the DT DET',
 'legal JJ ADJ',
 'officers NNS NOUN',
 ', , PUNCT',
 'he PRP PRON',
 'was VBD AUX',
 'repeatedly RB ADV',
 'warned VBN VERB',
 'that IN SCONJ',
 'it PRP PRON',
 'was VBD AUX',
 'not RB PART',
 'safe JJ ADJ',
 'for IN SCONJ',
 'him PRP PRON',
 'to TO PART',
 'appear VB VERB',
 'in IN ADP',
 'public JJ ADJ',
 ', , PUNCT',
 'or CC CCONJ',
 'to TO PART',
 'take VB VERB',
 'his PRP$ PRON',
 'daily JJ ADJ',
 'walk NN NOUN',
 ', , PUNCT',
 'as IN SCONJ',
 'he PRP PRON',
 'had VBD AUX',
 'done VBN VERB',
 ', , PUNCT',
 'unattended VBN VERB',
 'by IN ADP',
 'his PRP$ PRON',
 'friends NNS NOUN',
 ', , PUNCT',
 'in IN ADP',
 'the DT DET',
 'streets NNS NOUN',
 'of IN ADP',
 'the DT DET',
 'city NN NOUN',
 '. . PUNCT',
 'He PRP PRON',
 'was VBD AUX',
 'advised VBN VERB',
 'to TO PART',
 'withdraw VB VERB',
 'to IN ADP',
 'private JJ ADJ',
 'lodgings NNS NOUN',
 ', , PUNCT',
 'which WDT PRON',
 'were VBD AUX',
 'eagerly RB ADV',
 'offered VBN VERB',
 'him PRP PRON',
 'by IN ADP',
 'friends NNS NOUN',
 '. . PUNCT',
 'He PRP PRON',
 'rejected VBD VERB',
 'the DT DET',
 'advice NN NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'refused VBD VERB',
 'the DT DET',
 'offers NNS NOUN',
 ', , PUNCT',
 'saying VBG VERB',
 'that IN SCONJ',
 'he PRP PRON',
 'was VBD AUX',
 'old JJ ADJ',
 ', , PUNCT',
 'and CC CCONJ',
 'his PRP$ PRON',
 'life NN NOUN',
 'was VBD AUX',
 'not RB PART',
 'worth JJ ADJ',
 'much RB ADV',
 ', , PUNCT',
 'but CC CCONJ',
 'he PRP PRON',
 'had VBD VERB',
 'rather RB ADV',
 'the DT DET',
 'boys NNS NOUN',
 'should MD AUX',
 'troll VB VERB',
 'his PRP$ PRON',
 'old JJ ADJ',
 'head NN NOUN',
 'like IN ADP',
 'a DT DET',
 'football NN NOUN',
 'in IN ADP',
 'their PRP$ PRON',
 'streets NNS NOUN',
 ', , PUNCT',
 'than IN SCONJ',
 'that IN SCONJ',
 'he PRP PRON',
 'should MD AUX',
 'hide VB VERB',
 'it PRP PRON',
 '. . PUNCT',
 'And CC CCONJ',
 'he PRP PRON',
 'continued VBD VERB',
 'the DT DET',
 'uniform JJ ADJ',
 'practice NN NOUN',
 'of IN ADP',
 'his PRP$ PRON',
 'daily JJ ADJ',
 'walk NN NOUN',
 'into IN ADP',
 'all DT DET',
 'parts NNS NOUN',
 'of IN ADP',
 'the DT DET',
 'city NN NOUN',
 '. . PUNCT',
 'But CC CCONJ',
 'when WRB SCONJ',
 'the DT DET',
 'mob NN NOUN',
 'of IN ADP',
 'Charleston NNP PROPN',
 'was VBD AUX',
 'assembled VBN VERB',
 'in IN ADP',
 'the DT DET',
 'streets NNS NOUN',
 'before IN ADP',
 'his PRP$ PRON',
 'hotel NN NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'a DT DET',
 'deputation NN NOUN',
 'of IN ADP',
 'gentlemen NNS NOUN',
 'waited VBD VERB',
 'upon IN SCONJ',
 'him PRP PRON',
 'in IN ADP',
 'the DT DET',
 'hall NN NOUN',
 'to TO PART',
 'say VB VERB',
 'they PRP PRON',
 'had VBD AUX',
 'come VBN VERB',
 'with IN ADP',
 'the DT DET',
 'unanimous JJ ADJ',
 'voice NN NOUN',
 'of IN ADP',
 'the DT DET',
 'State NNP PROPN',
 'to TO PART',
 'remove VB VERB',
 'him PRP PRON',
 'by IN ADP',
 'force NN NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'the DT DET',
 'carriage NN NOUN',
 'was VBD AUX',
 'at IN ADP',
 'the DT DET',
 'door NN NOUN',
 ', , PUNCT',
 'he PRP PRON',
 'considered VBD VERB',
 'his PRP$ PRON',
 'duty NN NOUN',
 'discharged VBD VERB',
 'to IN ADP',
 'the DT DET',
 'last JJ ADJ',
 'point NN NOUN',
 'of IN ADP',
 'possibility NN NOUN',
 '. . PUNCT',
 'The DT DET',
 'force NN NOUN',
 'was VBD AUX',
 'apparent JJ ADJ',
 'and CC CCONJ',
 'irresistible JJ ADJ',
 '; : PUNCT',
 'the DT DET',
 'legal JJ ADJ',
 'officer NN NOUN',
 "'s POS PART",
 'part NN NOUN',
 'was VBD AUX',
 'up RB ADV',
 '; : PUNCT',
 'it PRP PRON',
 'was VBD AUX',
 'now RB ADV',
 'time NN NOUN',
 'for IN SCONJ',
 'the DT DET',
 'military JJ ADJ',
 'officer NN NOUN',
 'to TO PART',
 'be VB AUX',
 'sent VBN VERB',
 '; : PUNCT',
 'and CC CCONJ',
 'he PRP PRON',
 'said VBD VERB',
 ', , PUNCT',
 '“ `` PUNCT',
 'Well UH INTJ',
 ', , PUNCT',
 'gentlemen NNS NOUN',
 ', , PUNCT',
 'since IN SCONJ',
 'it PRP PRON',
 'is VBZ AUX',
 'your PRP$ PRON',
 'pleasure NN NOUN',
 'to TO PART',
 'use VB VERB',
 'force NN NOUN',
 ', , PUNCT',
 'I PRP PRON',
 'must MD AUX',
 'go VB VERB',
 '. . PUNCT',
 "” '' PUNCT",
 'But CC CCONJ',
 'his PRP$ PRON',
 'opinion NN NOUN',
 'was VBD AUX',
 'unchanged JJ ADJ',
 '. . PUNCT',
 '\n\n _SP SPACE',
 'In IN ADP',
 'like IN ADP',
 'manner NN NOUN',
 'now RB ADV',
 ', , PUNCT',
 'when WRB SCONJ',
 'the DT DET',
 'votes NNS NOUN',
 'of IN ADP',
 'the DT DET',
 'Free NNP PROPN',
 'States NNPS PROPN',
 ', , PUNCT',
 'as IN SCONJ',
 'shown VBN VERB',
 'in IN ADP',
 'the DT DET',
 'recent JJ ADJ',
 'election NN NOUN',
 'in IN ADP',
 'the DT DET',
 'State NNP PROPN',
 'of IN ADP',
 'Pennsylvania NNP PROPN',
 ', , PUNCT',
 'had VBD AUX',
 'disappointed VBN VERB',
 'the DT DET',
 'hopes NNS NOUN',
 'of IN ADP',
 'mankind NN NOUN',
 'and CC CCONJ',
 'betrayed VBD VERB',
 'the DT DET',
 'cause NN NOUN',
 'of IN ADP',
 'freedom NN NOUN',
 ', , PUNCT',
 'he PRP PRON',
 'considered VBD VERB',
 'the DT DET',
 'question NN NOUN',
 'of IN ADP',
 'justice NN NOUN',
 'and CC CCONJ',
 'liberty NN NOUN',
 ', , PUNCT',
 'for IN ADP',
 'his PRP$ PRON',
 'age NN NOUN',
 ', , PUNCT',
 'lost VBN VERB',
 ', , PUNCT',
 'and CC CCONJ',
 'had VBD VERB',
 'no RB ADV',
 'longer RBR ADV',
 'the DT DET',
 'will NN NOUN',
 'to TO PART',
 'drag VB VERB',
 'his PRP$ PRON',
 'days NNS NOUN',
 'through IN ADP',
 'the DT DET',
 'dishonours NNS NOUN',
 'of IN ADP',
 'the DT DET',
 'long JJ ADJ',
 'defeat NN NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'promptly RB ADV',
 'withdrew VBD VERB',
 ', , PUNCT',
 'but CC CCONJ',
 'with IN ADP',
 'unaltered JJ ADJ',
 'belief NN NOUN',
 '. . PUNCT',
 '\n\n _SP SPACE',
 'He PRP PRON',
 'was VBD AUX',
 'a DT DET',
 'very RB ADV',
 'natural JJ ADJ',
 ', , PUNCT',
 'but CC CCONJ',
 'a DT DET',
 'very RB ADV',
 'high JJ ADJ',
 'character NN NOUN',
 '; : PUNCT',
 'a DT DET',
 'man NN NOUN',
 'of IN ADP',
 'simple JJ ADJ',
 'tastes NNS NOUN',
 ', , PUNCT',
 'plain JJ ADJ',
 'and CC CCONJ',
 'true JJ ADJ',
 'in IN ADP',
 'speech NN NOUN',
 ', , PUNCT',
 'with IN ADP',
 'a DT DET',
 'clear JJ ADJ',
 'perception NN NOUN',
 'of IN ADP',
 'justice NN NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'a DT DET',
 'perfect JJ ADJ',
 'obedience NN NOUN',
 'thereto VBN VERB',
 'in IN ADP',
 'his PRP$ PRON',
 'action NN NOUN',
 '; : PUNCT',
 'of IN ADP',
 'a DT DET',
 'strong JJ ADJ',
 'understanding NN NOUN',
 ', , PUNCT',
 'precise JJ ADJ',
 'and CC CCONJ',
 'methodical JJ ADJ',
 ', , PUNCT',
 'which WDT PRON',
 'gave VBD VERB',
 'him PRP PRON',
 'great JJ ADJ',
 'eminence NN NOUN',
 'in IN ADP',
 'the DT DET',
 'legal JJ ADJ',
 'profession NN NOUN',
 '. . PUNCT',
 'It PRP PRON',
 'was VBD AUX',
 'rather RB ADV',
 'his PRP$ PRON',
 'reputation NN NOUN',
 'for IN ADP',
 'severe JJ ADJ',
 'method NN NOUN',
 'in IN ADP',
 'his PRP$ PRON',
 'intellect NN NOUN',
 'than IN ADP',
 'any DT DET',
 'special JJ ADJ',
 'direction NN NOUN',
 'in IN ADP',
 'his PRP$ PRON',
 'studies NNS NOUN',
 'that WDT PRON',
 'caused VBD VERB',
 'him PRP PRON',
 'to TO PART',
 'be VB AUX',
 'offered VBN VERB',
 'the DT DET',
 'mathematical JJ ADJ',
 'chair NN NOUN',
 'in IN ADP',
 'Harvard NNP PROPN',
 'University NNP PROPN',
 ', , PUNCT',
 'when WRB SCONJ',
 'vacant JJ ADJ',
 'in IN ADP',
 '1806 CD NUM',
 '. . PUNCT',
 'The DT DET',
 'severity NN NOUN',
 'of IN ADP',
 'his PRP$ PRON',
 'logic NN NOUN',
 'might MD AUX',
 'have VB AUX',
 'inspired VBN VERB',
 'fear NN NOUN',
 ', , PUNCT',
 'had VBD AUX',
 'it PRP PRON',
 'not RB PART',
 'been VBN AUX',
 'restrained VBN VERB',
 'by IN ADP',
 'his PRP$ PRON',
 'natural JJ ADJ',
 'reverence NN NOUN',
 ', , PUNCT',
 'which WDT PRON',
 'made VBD VERB',
 'him PRP PRON',
 'modest JJ ADJ',
 'and CC CCONJ',
 'courteous JJ ADJ',
 ', , PUNCT',
 'though IN SCONJ',
 'his PRP$ PRON',
 'courtesy NN NOUN',
 'had VBD VERB',
 'a DT DET',
 'grave NN NOUN',
 'and CC CCONJ',
 'almost RB ADV',
 'military JJ ADJ',
 'air NN NOUN',
 '. . PUNCT',
 'He PRP PRON',
 'combined VBD VERB',
 'a DT DET',
 'uniform JJ ADJ',
 'self NN NOUN',
 'respect NN NOUN',
 'with IN ADP',
 'a DT DET',
 'natural JJ ADJ',
 'reverence NN NOUN',
 'for IN ADP',
 'every DT DET',
 'other JJ ADJ',
 'man NN NOUN',
 '; : PUNCT',
 'so IN SCONJ',
 'that IN SCONJ',
 'it PRP PRON',
 'was VBD AUX',
 'perfectly RB ADV',
 'easy JJ ADJ',
 'for IN SCONJ',
 'him PRP PRON',
 'to TO PART',
 'associate VB VERB',
 'with IN ADP',
 'farmers NNS NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'with IN ADP',
 'plain JJ ADJ',
 ', , PUNCT',
 'uneducated JJ ADJ',
 ', , PUNCT',
 'poor JJ ADJ',
 'men NNS NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'he PRP PRON',
 'had VBD VERB',
 'a DT DET',
 'strong JJ ADJ',
 ', , PUNCT',
 'unaffected JJ ADJ',
 'interest NN NOUN',
 'in IN ADP',
 'farms NNS NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'crops NNS NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'weathers NNS NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'the DT DET',
 'common JJ ADJ',
 'incidents NNS NOUN',
 'of IN ADP',
 'rural JJ ADJ',
 'life NN NOUN',
 '. . PUNCT',
 'It PRP PRON',
 'was VBD AUX',
 'just RB ADV',
 'as RB ADV',
 'easy JJ ADJ',
 'for IN SCONJ',
 'him PRP PRON',
 'to TO PART',
 'meet VB VERB',
 'on IN ADP',
 'the DT DET',
 'same JJ ADJ',
 'floor NN NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'with IN ADP',
 'the DT DET',
 'same JJ ADJ',
 'plain JJ ADJ',
 'courtesy NN NOUN',
 ', , PUNCT',
 'men NNS NOUN',
 'of IN ADP',
 'distinction NN NOUN',
 'and CC CCONJ',
 'large JJ ADJ',
 'ability NN NOUN',
 '. . PUNCT',
 'He PRP PRON',
 'was VBD AUX',
 'fond JJ ADJ',
 'of IN ADP',
 'farms NNS NOUN',
 'and CC CCONJ',
 'trees NNS NOUN',
 ', , PUNCT',
 'fond JJ ADJ',
 'of IN ADP',
 'birds NNS NOUN',
 ', , PUNCT',
 'and CC CCONJ',
 'attentive VB VERB',
 'to IN ADP',
 'their PRP$ PRON',
 'manners NNS NOUN',
 'and CC CCONJ',
 'habits NNS NOUN',
 '; : PUNCT',
 'addicted VBN VERB',
 'to IN ADP',
 'long JJ ADJ',
 'and CC CCONJ',
 'retired JJ ADJ',
 'walks NNS NOUN',
 '; : PUNCT',
 'temperate VB VERB',
 'to IN ADP',
 'asceticism RB ADV',
 ', , PUNCT',
 'for IN ADP',
 'no DT DET',
 'lesson NN NOUN',
 'of IN ADP',
 'his PRP$ PRON',
 'experience NN NOUN',
 'was VBD AUX',
 'lost VBN VERB',
 'on IN ADP',
 'him PRP PRON',
 ', , PUNCT',
 'and CC CCONJ',
 'his PRP$ PRON',
 'self NN NOUN',
 'command NN NOUN',
 'was VBD AUX',
 'perfect JJ ADJ',
 '. . PUNCT',
 'Though IN SCONJ',
 'rich JJ ADJ',
 ', , PUNCT',
 'of IN ADP',
 'a DT DET',
 'plainness NN NOUN',
 'and CC CCONJ',
 'almost RB ADV',
 'poverty NN NOUN',
 'of IN ADP',
 'personal JJ ADJ',
 'expenditure NN NOUN',
 ', , PUNCT',
 'yet RB ADV',
 'liberal JJ ADJ',
 'of IN ADP',
 'his PRP$ PRON',
 'money NN NOUN',
 ...]

## Convert POS output to dataframe

In [31]:
pos_df = pd.DataFrame(pos_output)

In [32]:
pos_df[['word','pos_tag', 'pos']] = pos_df[0].str.split(" ", 3, expand=True)
pos_df = pos_df.drop(pos_df.columns[0], axis=1)

/var/folders/k4/nyqsgzvx72vch3f9mypnvg640000gp/T/ipykernel_45632/4195826159.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  pos_df[['word','pos_tag', 'pos']] = pos_df[0].str.split(" ", 3, expand=True)

In [33]:
pos_df

         word pos_tag    pos
0      SAMUEL     NNP  PROPN
1        HOAR     NNP  PROPN
2           .       .  PUNCT
3        \n\n     _SP  SPACE
4           “      ``  PUNCT
...       ...     ...    ...
3377      his    PRP$   PRON
3378  liberal      JJ    ADJ
3379     hand      NN   NOUN
3380        .       .  PUNCT
3381   \n\n\n     _SP  SPACE

[3382 rows x 3 columns]

In [34]:
# tag corpus with NER data
doc = nlp(corpus[0])
ner_output = []
for token in doc:
    ner_output.append(token.text + " " + token.ent_type_)

In [35]:
ner_output

['SAMUEL ',
 'HOAR ',
 '. ',
 '\n\n ',
 '“ ',
 'Magno GPE',
 'southeast ',
 'judice ',
 'quisque ',
 'tuetur ',
 '; ',
 '\n\n ',
 'Victrix GPE',
 'causa ',
 'deis ',
 'placuit ',
 'sed ',
 'victa ',
 'Catoni ORG',
 '. ',
 '” ',
 '\n\n\n\n\n\n ',
 'A DATE',
 'YEAR DATE',
 'ago DATE',
 ', ',
 'how ',
 'often ',
 'did ',
 'we ',
 'meet ',
 '\n\n ',
 'Beneath ',
 'these ',
 'elms ',
 ', ',
 'once ',
 'more ',
 'in ',
 'sober ',
 'bloom ',
 ', ',
 '\n\n ',
 'Thy ',
 'tall ',
 ', ',
 'sad ',
 'figure ',
 'pacing ',
 'down ',
 'the ',
 'street ',
 ', ',
 '\n\n ',
 'And ',
 'now ',
 'the ',
 'robin ',
 'sings ',
 'above ',
 'thy ',
 'tomb ',
 '! ',
 '\n\n ',
 'Thy ',
 'name ',
 'on ',
 'other ',
 'shores ',
 'may ',
 'never ',
 'be ',
 'known ',
 ', ',
 '\n\n ',
 'Though ',
 'Rome GPE',
 'austere ',
 'no ',
 'graver ',
 'consul ',
 'knew ',
 ', ',
 '\n\n ',
 'But ',
 'Massachusetts GPE',
 'her ',
 'true ',
 'son ',
 'shall ',
 'own ',
 '; ',
 '\n\n ',
 'Out ',
 'of ',
 'her ',
 'soil ',
 'thy ',
 'hardy ',
 'virtues ',
 'grew ',
 '. ',
 '\n\n ',
 'She ',
 'loves ',
 'the ',
 'man ',
 'that ',
 'chose ',
 'the ',
 'conquered ',
 'cause ',
 ', ',
 '\n\n ',
 'With ',
 'upright ',
 'soul ',
 'that ',
 'bowed ',
 'to ',
 'God ',
 'alone ',
 '; ',
 '\n\n ',
 'The ',
 'clean ',
 'hands ',
 'that ',
 'upheld ',
 'her ',
 'equal ',
 'laws ',
 ', ',
 '\n\n ',
 'The ',
 'old ',
 'religion ',
 'never ',
 'to ',
 'be ',
 'outgrown ',
 '; ',
 '\n\n ',
 'The ',
 'cold ',
 'demeanour ',
 ', ',
 'the ',
 'warm ',
 'heart ',
 'beneath ',
 ', ',
 '\n\n ',
 'The ',
 'simple ',
 'grandeur ',
 'of ',
 'thy ',
 'life ',
 'and ',
 'death ',
 '. ',
 '\n\n ',
 'F. PERSON',
 'B. PERSON',
 'SANBORN PERSON',
 '. ',
 '\n\n ',
 'April DATE',
 ', DATE',
 '1857 DATE',
 '. ',
 '\n\n\n\n\n\n ',
 'SAMUEL ',
 'HOAR ',
 '. ',
 '\n\n ',
 'HERE ',
 'is ',
 'a DATE',
 'day DATE',
 'on ',
 'which ',
 'more ',
 'public ',
 'good ',
 'or ',
 'evil ',
 'is ',
 'to ',
 'be ',
 'done ',
 'than ',
 'was ',
 'ever ',
 'done ',
 'on ',
 'any DATE',
 'day DATE',
 '. ',
 'And ',
 'this ',
 'is ',
 'the ',
 'pregnant ',
 'season DATE',
 ', ',
 'when ',
 'our ',
 'old ',
 'Roman PERSON',
 ', ',
 'Samuel PERSON',
 'Hoar PERSON',
 ', ',
 'has ',
 'chosen ',
 'to ',
 'quit ',
 'this ',
 'world ',
 '. ',
 'Ab ',
 'iniquo ',
 'certamine ',
 'indignabundus ',
 'recessit ',
 '. ',
 '\n\n ',
 'He ',
 'was ',
 'born ',
 'under ',
 'a ',
 'Christian NORP',
 'and ',
 'humane ',
 'star ',
 ', ',
 'full ',
 'of ',
 'mansuetude ',
 'and ',
 'nobleness ',
 ', ',
 'honour ',
 'and ',
 'charity ',
 '; ',
 'and ',
 ', ',
 'whilst ',
 'he ',
 'was ',
 'willing ',
 'to ',
 'face ',
 'every ',
 'disagreeable ',
 'duty ',
 ', ',
 'whilst ',
 'he ',
 'dared ',
 'to ',
 'do ',
 'all ',
 'that ',
 'might ',
 'beseem ',
 'a ',
 'man ',
 ', ',
 'his ',
 'self ',
 'respect ',
 'restrained ',
 'him ',
 'from ',
 'any ',
 'foolhardiness ',
 '. ',
 'The ',
 'Homeric ORG',
 'heroes ',
 ', ',
 'when ',
 'they ',
 'saw ',
 'the ',
 'gods ',
 'mingling ',
 'in ',
 'the ',
 'fray ',
 ', ',
 'sheathed ',
 'their ',
 'swords ',
 '. ',
 'So ',
 'did ',
 'not ',
 'he ',
 'feel ',
 'any ',
 'call ',
 'to ',
 'make ',
 'it ',
 'a ',
 'contest ',
 'of ',
 'personal ',
 'strength ',
 'with ',
 'mobs ',
 'or ',
 'nations ',
 '; ',
 'but ',
 'when ',
 'he ',
 'saw ',
 'the DATE',
 'day DATE',
 'and ',
 'the ',
 'gods ',
 'went ',
 'against ',
 'him ',
 ', ',
 'he ',
 'withdrew ',
 ', ',
 'but ',
 'with ',
 'an ',
 'unaltered ',
 'belief ',
 '. ',
 'All ',
 'was ',
 'conquered ',
 'prœter ',
 'atrocem ',
 'animum ',
 'Catonis ORG',
 '. ',
 '\n\n ',
 'At ',
 'the ',
 'time ',
 'when ',
 'he ',
 'went ',
 'to ',
 'South GPE',
 'Carolina GPE',
 'as ',
 'the ',
 'Commissioner ',
 'of ',
 'Massachusetts GPE',
 ', ',
 'in ',
 '1844 DATE',
 ', ',
 'whilst ',
 'staying ',
 'in ',
 'Charleston GPE',
 ', ',
 'pending ',
 'his ',
 'correspondence ',
 'with ',
 'the ',
 'governor ',
 'and ',
 'the ',
 'legal ',
 'officers ',
 ', ',
 'he ',
 'was ',
 'repeatedly ',
 'warned ',
 'that ',
 'it ',
 'was ',
 'not ',
 'safe ',
 'for ',
 'him ',
 'to ',
 'appear ',
 'in ',
 'public ',
 ', ',
 'or ',
 'to ',
 'take ',
 'his ',
 'daily DATE',
 'walk ',
 ', ',
 'as ',
 'he ',
 'had ',
 'done ',
 ', ',
 'unattended ',
 'by ',
 'his ',
 'friends ',
 ', ',
 'in ',
 'the ',
 'streets ',
 'of ',
 'the ',
 'city ',
 '. ',
 'He ',
 'was ',
 'advised ',
 'to ',
 'withdraw ',
 'to ',
 'private ',
 'lodgings ',
 ', ',
 'which ',
 'were ',
 'eagerly ',
 'offered ',
 'him ',
 'by ',
 'friends ',
 '. ',
 'He ',
 'rejected ',
 'the ',
 'advice ',
 ', ',
 'and ',
 'refused ',
 'the ',
 'offers ',
 ', ',
 'saying ',
 'that ',
 'he ',
 'was ',
 'old ',
 ', ',
 'and ',
 'his ',
 'life ',
 'was ',
 'not ',
 'worth ',
 'much ',
 ', ',
 'but ',
 'he ',
 'had ',
 'rather ',
 'the ',
 'boys ',
 'should ',
 'troll ',
 'his ',
 'old ',
 'head ',
 'like ',
 'a ',
 'football ',
 'in ',
 'their ',
 'streets ',
 ', ',
 'than ',
 'that ',
 'he ',
 'should ',
 'hide ',
 'it ',
 '. ',
 'And ',
 'he ',
 'continued ',
 'the ',
 'uniform ',
 'practice ',
 'of ',
 'his ',
 'daily DATE',
 'walk ',
 'into ',
 'all ',
 'parts ',
 'of ',
 'the ',
 'city ',
 '. ',
 'But ',
 'when ',
 'the ',
 'mob ',
 'of ',
 'Charleston GPE',
 'was ',
 'assembled ',
 'in ',
 'the ',
 'streets ',
 'before ',
 'his ',
 'hotel ',
 ', ',
 'and ',
 'a ',
 'deputation ',
 'of ',
 'gentlemen ',
 'waited ',
 'upon ',
 'him ',
 'in ',
 'the ',
 'hall ',
 'to ',
 'say ',
 'they ',
 'had ',
 'come ',
 'with ',
 'the ',
 'unanimous ',
 'voice ',
 'of ',
 'the ',
 'State ORG',
 'to ',
 'remove ',
 'him ',
 'by ',
 'force ',
 ', ',
 'and ',
 'the ',
 'carriage ',
 'was ',
 'at ',
 'the ',
 'door ',
 ', ',
 'he ',
 'considered ',
 'his ',
 'duty ',
 'discharged ',
 'to ',
 'the ',
 'last ',
 'point ',
 'of ',
 'possibility ',
 '. ',
 'The ',
 'force ',
 'was ',
 'apparent ',
 'and ',
 'irresistible ',
 '; ',
 'the ',
 'legal ',
 'officer ',
 "'s ",
 'part ',
 'was ',
 'up ',
 '; ',
 'it ',
 'was ',
 'now ',
 'time ',
 'for ',
 'the ',
 'military ',
 'officer ',
 'to ',
 'be ',
 'sent ',
 '; ',
 'and ',
 'he ',
 'said ',
 ', ',
 '“ ',
 'Well ',
 ', ',
 'gentlemen ',
 ', ',
 'since ',
 'it ',
 'is ',
 'your ',
 'pleasure ',
 'to ',
 'use ',
 'force ',
 ', ',
 'I ',
 'must ',
 'go ',
 '. ',
 '” ',
 'But ',
 'his ',
 'opinion ',
 'was ',
 'unchanged ',
 '. ',
 '\n\n ',
 'In ',
 'like ',
 'manner ',
 'now ',
 ', ',
 'when ',
 'the ',
 'votes ',
 'of ',
 'the GPE',
 'Free GPE',
 'States GPE',
 ', ',
 'as ',
 'shown ',
 'in ',
 'the ',
 'recent ',
 'election ',
 'in ',
 'the GPE',
 'State GPE',
 'of GPE',
 'Pennsylvania GPE',
 ', ',
 'had ',
 'disappointed ',
 'the ',
 'hopes ',
 'of ',
 'mankind ',
 'and ',
 'betrayed ',
 'the ',
 'cause ',
 'of ',
 'freedom ',
 ', ',
 'he ',
 'considered ',
 'the ',
 'question ',
 'of ',
 'justice ',
 'and ',
 'liberty ',
 ', ',
 'for ',
 'his ',
 'age ',
 ', ',
 'lost ',
 ', ',
 'and ',
 'had ',
 'no ',
 'longer ',
 'the ',
 'will ',
 'to ',
 'drag ',
 'his ',
 'days ',
 'through ',
 'the ',
 'dishonours ',
 'of ',
 'the ',
 'long ',
 'defeat ',
 ', ',
 'and ',
 'promptly ',
 'withdrew ',
 ', ',
 'but ',
 'with ',
 'unaltered ',
 'belief ',
 '. ',
 '\n\n ',
 'He ',
 'was ',
 'a ',
 'very ',
 'natural ',
 ', ',
 'but ',
 'a ',
 'very ',
 'high ',
 'character ',
 '; ',
 'a ',
 'man ',
 'of ',
 'simple ',
 'tastes ',
 ', ',
 'plain ',
 'and ',
 'true ',
 'in ',
 'speech ',
 ', ',
 'with ',
 'a ',
 'clear ',
 'perception ',
 'of ',
 'justice ',
 ', ',
 'and ',
 'a ',
 'perfect ',
 'obedience ',
 'thereto ',
 'in ',
 'his ',
 'action ',
 '; ',
 'of ',
 'a ',
 'strong ',
 'understanding ',
 ', ',
 'precise ',
 'and ',
 'methodical ',
 ', ',
 'which ',
 'gave ',
 'him ',
 'great ',
 'eminence ',
 'in ',
 'the ',
 'legal ',
 'profession ',
 '. ',
 'It ',
 'was ',
 'rather ',
 'his ',
 'reputation ',
 'for ',
 'severe ',
 'method ',
 'in ',
 'his ',
 'intellect ',
 'than ',
 'any ',
 'special ',
 'direction ',
 'in ',
 'his ',
 'studies ',
 'that ',
 'caused ',
 'him ',
 'to ',
 'be ',
 'offered ',
 'the ',
 'mathematical ',
 'chair ',
 'in ',
 'Harvard ORG',
 'University ORG',
 ', ',
 'when ',
 'vacant ',
 'in ',
 '1806 DATE',
 '. ',
 'The ',
 'severity ',
 'of ',
 'his ',
 'logic ',
 'might ',
 'have ',
 'inspired ',
 'fear ',
 ', ',
 'had ',
 'it ',
 'not ',
 'been ',
 'restrained ',
 'by ',
 'his ',
 'natural ',
 'reverence ',
 ', ',
 'which ',
 'made ',
 'him ',
 'modest ',
 'and ',
 'courteous ',
 ', ',
 'though ',
 'his ',
 'courtesy ',
 'had ',
 'a ',
 'grave ',
 'and ',
 'almost ',
 'military ',
 'air ',
 '. ',
 'He ',
 'combined ',
 'a ',
 'uniform ',
 'self ',
 'respect ',
 'with ',
 'a ',
 'natural ',
 'reverence ',
 'for ',
 'every ',
 'other ',
 'man ',
 '; ',
 'so ',
 'that ',
 'it ',
 'was ',
 'perfectly ',
 'easy ',
 'for ',
 'him ',
 'to ',
 'associate ',
 'with ',
 'farmers ',
 ', ',
 'and ',
 'with ',
 'plain ',
 ', ',
 'uneducated ',
 ', ',
 'poor ',
 'men ',
 ', ',
 'and ',
 'he ',
 'had ',
 'a ',
 'strong ',
 ', ',
 'unaffected ',
 'interest ',
 'in ',
 'farms ',
 ', ',
 'and ',
 'crops ',
 ', ',
 'and ',
 'weathers ',
 ', ',
 'and ',
 'the ',
 'common ',
 'incidents ',
 'of ',
 'rural ',
 'life ',
 '. ',
 'It ',
 'was ',
 'just ',
 'as ',
 'easy ',
 'for ',
 'him ',
 'to ',
 'meet ',
 'on ',
 'the ',
 'same ',
 'floor ',
 ', ',
 'and ',
 'with ',
 'the ',
 'same ',
 'plain ',
 'courtesy ',
 ', ',
 'men ',
 'of ',
 'distinction ',
 'and ',
 'large ',
 'ability ',
 '. ',
 'He ',
 'was ',
 'fond ',
 'of ',
 'farms ',
 'and ',
 'trees ',
 ', ',
 'fond ',
 'of ',
 'birds ',
 ', ',
 'and ',
 'attentive ',
 'to ',
 'their ',
 'manners ',
 'and ',
 'habits ',
 '; ',
 'addicted ',
 'to ',
 'long ',
 'and ',
 'retired ',
 'walks ',
 '; ',
 'temperate ',
 'to ',
 'asceticism ',
 ', ',
 'for ',
 'no ',
 'lesson ',
 'of ',
 'his ',
 'experience ',
 'was ',
 'lost ',
 'on ',
 'him ',
 ', ',
 'and ',
 'his ',
 'self ',
 'command ',
 'was ',
 'perfect ',
 '. ',
 'Though ',
 'rich ',
 ', ',
 'of ',
 'a ',
 'plainness ',
 'and ',
 'almost ',
 'poverty ',
 'of ',
 'personal ',
 'expenditure ',
 ', ',
 'yet ',
 'liberal ',
 'of ',
 'his ',
 'money ',
 ...]

## Convert NER output to dataframe and split columns to allow for easier cleaning

In [36]:
ner_df = pd.DataFrame(ner_output)

In [39]:
ner_df[['word','entity_type']] = ner_df[0].str.split(" ", 2, expand=True)
ner_df = ner_df.drop(ner_df.columns[0], axis=1)

/var/folders/k4/nyqsgzvx72vch3f9mypnvg640000gp/T/ipykernel_45632/2030630874.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  ner_df[['word','entity_type']] = ner_df[0].str.split(" ", 2, expand=True)

In [40]:
print(ner_df.to_string())

                 word entity_type
0              SAMUEL
1                HOAR
2                   .
3                \n\n
4                   “
5               Magno         GPE
6           southeast
7              judice
8             quisque
9              tuetur
10                  ;
11               \n\n
12            Victrix         GPE
13              causa
14               deis
15            placuit
16                sed
17              victa
18             Catoni         ORG
19                  .
20                  ”
21       \n\n\n\n\n\n
22                  A        DATE
23               YEAR        DATE
24                ago        DATE
25                  ,
26                how
27              often
28                did
29                 we
30               meet
31               \n\n
32            Beneath
33              these
34               elms
35                  ,
36               once
37               more
38                 in
39              sober
40              bloom
41                  ,
42               \n\n
43                Thy
44               tall
45                  ,
46                sad
47             figure
48             pacing
49               down
50                the
51             street
52                  ,
53               \n\n
54                And
55                now
56                the
57              robin
58              sings
59              above
60                thy
61               tomb
62                  !
63               \n\n
64                Thy
65               name
66                 on
67              other
68             shores
69                may
70              never
71                 be
72              known
73                  ,
74               \n\n
75             Though
76               Rome         GPE
77            austere
78                 no
79             graver
80             consul
81               knew
82                  ,
83               \n\n
84                But
85      Massachusetts         GPE
86                her
87               true
88                son
89              shall
90                own
91                  ;
92               \n\n
93                Out
94                 of
95                her
96               soil
97                thy
98              hardy
99            virtues
100              grew
101                 .
102              \n\n
103               She
104             loves
105               the
106               man
107              that
108             chose
109               the
110         conquered
111             cause
112                 ,
113              \n\n
114              With
115           upright
116              soul
117              that
118             bowed
119                to
120               God
121             alone
122                 ;
123              \n\n
124               The
125             clean
126             hands
127              that
128            upheld
129               her
130             equal
131              laws
132                 ,
133              \n\n
134               The
135               old
136          religion
137             never
138                to
139                be
140          outgrown
141                 ;
142              \n\n
143               The
144              cold
145         demeanour
146                 ,
147               the
148              warm
149             heart
150           beneath
151                 ,
152              \n\n
153               The
154            simple
155          grandeur
156                of
157               thy
158              life
159               and
160             death
161                 .
162              \n\n
163                F.      PERSON
164                B.      PERSON
165           SANBORN      PERSON
166                 .
167              \n\n
168             April        DATE
169                 ,        DATE
170              1857        DATE
171                 .
172      \n\n\n\n\n\n
173            SAMUEL
174              HOAR
175                 .
176              \n\n
177              HERE
178                is
179                 a        DATE
180               day        DATE
181                on
182             which
183              more
184            public
185              good
186                or
187              evil
188                is
189                to
190                be
191              done
192              than
193               was
194              ever
195              done
196                on
197               any        DATE
198               day        DATE
199                 .
200               And
201              this
202                is
203               the
204          pregnant
205            season        DATE
206                 ,
207              when
208               our
209               old
210             Roman      PERSON
211                 ,
212            Samuel      PERSON
213              Hoar      PERSON
214                 ,
215               has
216            chosen
217                to
218              quit
219              this
220             world
221                 .
222                Ab
223            iniquo
224         certamine
225     indignabundus
226          recessit
227                 .
228              \n\n
229                He
230               was
231              born
232             under
233                 a
234         Christian        NORP
235               and
236            humane
237              star
238                 ,
239              full
240                of
241        mansuetude
242               and
243         nobleness
244                 ,
245            honour
246               and
247           charity
248                 ;
249               and
250                 ,
251            whilst
252                he
253               was
254           willing
255                to
256              face
257             every
258      disagreeable
259              duty
260                 ,
261            whilst
262                he
263             dared
264                to
265                do
266               all
267              that
268             might
269            beseem
270                 a
271               man
272                 ,
273               his
274              self
275           respect
276        restrained
277               him
278              from
279               any
280     foolhardiness
281                 .
282               The
283           Homeric         ORG
284            heroes
285                 ,
286              when
287              they
288               saw
289               the
290              gods
291          mingling
292                in
293               the
294              fray
295                 ,
296          sheathed
297             their
298            swords
299                 .
300                So
301               did
302               not
303                he
304              feel
305               any
306              call
307                to
308              make
309                it
310                 a
311           contest
312                of
313          personal
314          strength
315              with
316              mobs
317                or
318           nations
319                 ;
320               but
321              when
322                he
323               saw
324               the        DATE
325               day        DATE
326               and
327               the
328              gods
329              went
330           against
331               him
332                 ,
333                he
334          withdrew
335                 ,
336               but
337              with
338                an
339         unaltered
340            belief
341                 .
342               All
343               was
344         conquered
345            prœter
346           atrocem
347            animum
348           Catonis         ORG
349                 .
350              \n\n
351                At
352               the
353              time
354              when
355                he
356              went
357                to
358             South         GPE
359          Carolina         GPE
360                as
361               the
362      Commissioner
363                of
364     Massachusetts         GPE
365                 ,
366                in
367              1844        DATE
368                 ,
369            whilst
370           staying
371                in
372        Charleston         GPE
373                 ,
374           pending
375               his
376    correspondence
377              with
378               the
379          governor
380               and
381               the
382             legal
383          officers
384                 ,
385                he
386               was
387        repeatedly
388            warned
389              that
390                it
391               was
392               not
393              safe
394               for
395               him
396                to
397            appear
398                in
399            public
400                 ,
401                or
402                to
403              take
404               his
405             daily        DATE
406              walk
407                 ,
408                as
409                he
410               had
411              done
412                 ,
413        unattended
414                by
415               his
416           friends
417                 ,
418                in
419               the
420           streets
421                of
422               the
423              city
424                 .
425                He
426               was
427           advised
428                to
429          withdraw
430                to
431           private
432          lodgings
433                 ,
434             which
435              were
436           eagerly
437           offered
438               him
439                by
440           friends
441                 .
442                He
443          rejected
444               the
445            advice
446                 ,
447               and
448           refused
449               the
450            offers
451                 ,
452            saying
453              that
454                he
455               was
456               old
457                 ,
458               and
459               his
460              life
461               was
462               not
463             worth
464              much
465                 ,
466               but
467                he
468               had
469            rather
470               the
471              boys
472            should
473             troll
474               his
475               old
476              head
477              like
478                 a
479          football
480                in
481             their
482           streets
483                 ,
484              than
485              that
486                he
487            should
488              hide
489                it
490                 .
491               And
492                he
493         continued
494               the
495           uniform
496          practice
497                of
498               his
499             daily        DATE
500              walk
501              into
502               all
503             parts
504                of
505               the
506              city
507                 .
508               But
509              when
510               the
511               mob
512                of
513        Charleston         GPE
514               was
515         assembled
516                in
517               the
518           streets
519            before
520               his
521             hotel
522                 ,
523               and
524                 a
525        deputation
526                of
527         gentlemen
528            waited
529              upon
530               him
531                in
532               the
533              hall
534                to
535               say
536              they
537               had
538              come
539              with
540               the
541         unanimous
542             voice
543                of
544               the
545             State         ORG
546                to
547            remove
548               him
549                by
550             force
551                 ,
552               and
553               the
554          carriage
555               was
556                at
557               the
558              door
559                 ,
560                he
561        considered
562               his
563              duty
564        discharged
565                to
566               the
567              last
568             point
569                of
570       possibility
571                 .
572               The
573             force
574               was
575          apparent
576               and
577      irresistible
578                 ;
579               the
580             legal
581           officer
582                's
583              part
584               was
585                up
586                 ;
587                it
588               was
589               now
590              time
591               for
592               the
593          military
594           officer
595                to
596                be
597              sent
598                 ;
599               and
600                he
601              said
602                 ,
603                 “
604              Well
605                 ,
606         gentlemen
607                 ,
608             since
609                it
610                is
611              your
612          pleasure
613                to
614               use
615             force
616                 ,
617                 I
618              must
619                go
620                 .
621                 ”
622               But
623               his
624           opinion
625               was
626         unchanged
627                 .
628              \n\n
629                In
630              like
631            manner
632               now
633                 ,
634              when
635               the
636             votes
637                of
638               the         GPE
639              Free         GPE
640            States         GPE
641                 ,
642                as
643             shown
644                in
645               the
646            recent
647          election
648                in
649               the         GPE
650             State         GPE
651                of         GPE
652      Pennsylvania         GPE
653                 ,
654               had
655      disappointed
656               the
657             hopes
658                of
659           mankind
660               and
661          betrayed
662               the
663             cause
664                of
665           freedom
666                 ,
667                he
668        considered
669               the
670          question
671                of
672           justice
673               and
674           liberty
675                 ,
676               for
677               his
678               age
679                 ,
680              lost
681                 ,
682               and
683               had
684                no
685            longer
686               the
687              will
688                to
689              drag
690               his
691              days
692           through
693               the
694        dishonours
695                of
696               the
697              long
698            defeat
699                 ,
700               and
701          promptly
702          withdrew
703                 ,
704               but
705              with
706         unaltered
707            belief
708                 .
709              \n\n
710                He
711               was
712                 a
713              very
714           natural
715                 ,
716               but
717                 a
718              very
719              high
720         character
721                 ;
722                 a
723               man
724                of
725            simple
726            tastes
727                 ,
728             plain
729               and
730              true
731                in
732            speech
733                 ,
734              with
735                 a
736             clear
737        perception
738                of
739           justice
740                 ,
741               and
742                 a
743           perfect
744         obedience
745           thereto
746                in
747               his
748            action
749                 ;
750                of
751                 a
752            strong
753     understanding
754                 ,
755           precise
756               and
757        methodical
758                 ,
759             which
760              gave
761               him
762             great
763          eminence
764                in
765               the
766             legal
767        profession
768                 .
769                It
770               was
771            rather
772               his
773        reputation
774               for
775            severe
776            method
777                in
778               his
779         intellect
780              than
781               any
782           special
783         direction
784                in
785               his
786           studies
787              that
788            caused
789               him
790                to
791                be
792           offered
793               the
794      mathematical
795             chair
796                in
797           Harvard         ORG
798        University         ORG
799                 ,
800              when
801            vacant
802                in
803              1806        DATE
804                 .
805               The
806          severity
807                of
808               his
809             logic
810             might
811              have
812          inspired
813              fear
814                 ,
815               had
816                it
817               not
818              been
819        restrained
820                by
821               his
822           natural
823         reverence
824                 ,
825             which
826              made
827               him
828            modest
829               and
830         courteous
831                 ,
832            though
833               his
834          courtesy
835               had
836                 a
837             grave
838               and
839            almost
840          military
841               air
842                 .
843                He
844          combined
845                 a
846           uniform
847              self
848           respect
849              with
850                 a
851           natural
852         reverence
853               for
854             every
855             other
856               man
857                 ;
858                so
859              that
860                it
861               was
862         perfectly
863              easy
864               for
865               him
866                to
867         associate
868              with
869           farmers
870                 ,
871               and
872              with
873             plain
874                 ,
875        uneducated
876                 ,
877              poor
878               men
879                 ,
880               and
881                he

# Data Cleaning

Only preserve those rows where an NER classification was given

In [45]:
import numpy as np
ner_df['entity_type'].replace('', np.nan, inplace=True)

In [47]:
ner_df.dropna(subset=['entity_type'], inplace=True)

In [48]:
ner_df

            word entity_type
5          Magno         GPE
12       Victrix         GPE
18        Catoni         ORG
22             A        DATE
23          YEAR        DATE
...          ...         ...
3249   Education         ORG
3255  University         ORG
3353    December        DATE
3367        July        DATE
3375     October        DATE

[137 rows x 2 columns]